// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Status {
    "running": boolean;
    "starting": boolean;
    "attached": boolean;
    "port": number;
    "url": string;
    "pid": number;
    "binaryPath": string;
    "dataDir": string;
    "health": { [_: string]: any };
    "lastError": string;
    "logs": string[];

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("starting" in $$source)) {
            this["starting"] = false;
        }
        if (!("attached" in $$source)) {
            this["attached"] = false;
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("binaryPath" in $$source)) {
            this["binaryPath"] = "";
        }
        if (!("dataDir" in $$source)) {
            this["dataDir"] = "";
        }
        if (!("health" in $$source)) {
            this["health"] = {};
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }
        if (!("logs" in $$source)) {
            this["logs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        const $$createField8_0 = $$createType0;
        const $$createField10_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("health" in $$parsedSource) {
            $$parsedSource["health"] = $$createField8_0($$parsedSource["health"]);
        }
        if ("logs" in $$parsedSource) {
            $$parsedSource["logs"] = $$createField10_0($$parsedSource["logs"]);
        }
        return new Status($$parsedSource as Partial<Status>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
