export type SupportedLocale = 'en' | 'id' | 'zh-CN'

export type MessageKey =
  | 'app.auth.verifyingTitle'
  | 'app.auth.verifyingBody'
  | 'app.auth.inputLabel'
  | 'app.auth.inputRequired'
  | 'app.auth.submit'
  | 'app.auth.securityTitle'
  | 'app.auth.securityItem1'
  | 'app.auth.securityItem2'
  | 'app.auth.securityItem3'
  | 'app.auth.securityItem4'
  | 'app.auth.securityItem5'
  | 'app.tabs.messages'
  | 'app.tabs.chat'
  | 'app.tabs.responses'
  | 'app.tabs.gemini'
  | 'app.tabs.images'
  | 'app.tabs.conversations'
  | 'cockpit.overrideActive'
  | 'cockpit.restoreDefault'
  | 'cockpit.empty'
  | 'app.header.logout'
  | 'app.stats.trafficTitle'
  | 'app.stats.totalChannels'
  | 'app.stats.totalChannelsDesc'
  | 'app.stats.activeChannels'
  | 'app.stats.activeChannelsDesc'
  | 'app.stats.systemStatus'
  | 'app.actions.addChannel'
  | 'app.actions.ping'
  | 'app.actions.refresh'
  | 'app.dialog.addApiKeyTitle'
  | 'app.dialog.apiKeyLabel'
  | 'app.dialog.apiKeyPlaceholder'
  | 'app.actions.cancel'
  | 'app.actions.add'
  | 'common.enabled'
  | 'common.disabled'
  | 'common.autoGenerated'
  | 'channels.empty.title'
  | 'channels.empty.description'
  | 'channels.empty.button'
  | 'capability.title'
  | 'capability.fetchingModels'
  | 'capability.selectModels'
  | 'capability.selectAll'
  | 'capability.deselectAll'
  | 'capability.noModelsFound'
  | 'capability.addModelLabel'
  | 'capability.addModelPlaceholder'
  | 'capability.startTest'
  | 'capability.loadingTitle'
  | 'capability.notStarted'
  | 'capability.rpmLabel'
  | 'capability.compatibleProtocols'
  | 'capability.noCompatibleProtocols'
  | 'capability.table.protocol'
  | 'capability.table.status'
  | 'capability.table.successCount'
  | 'capability.table.latency'
  | 'capability.table.streaming'
  | 'capability.table.actions'
  | 'capability.modelDetails'
  | 'capability.modelDetailsUnavailable'
  | 'capability.attemptedModels'
  | 'capability.startedAt'
  | 'capability.testedAt'
  | 'capability.success'
  | 'capability.failed'
  | 'capability.failedTooltip'
  | 'capability.tooltipLatency'
  | 'capability.tooltipStreaming'
  | 'capability.modelsLabel'
  | 'capability.supported'
  | 'capability.unsupported'
  | 'capability.copyToTab'
  | 'capability.currentTab'
  | 'capability.convert'
  | 'capability.channelFallback'
  | 'capability.progressSummary'
  | 'capability.protocolRunning'
  | 'capability.modelStatus'
  | 'capability.modelQueued'
  | 'capability.modelRunning'
  | 'capability.modelSuccess'
  | 'capability.modelFailed'
  | 'capability.modelSkipped'
  | 'capability.cancel'
  | 'capability.cancelling'
  | 'capability.cancelled'
  | 'capability.partial'
  | 'capability.runModeCacheHit'
  | 'capability.runModeReusedRunning'
  | 'capability.runModeResumedCancelled'
  | 'capability.runModeReusedPreviousResults'
  | 'capability.reasonNotRun'
  | 'capability.reasonCancelled'
  | 'capability.reasonTimeout'
  | 'capability.retryModel'
  | 'capability.testModel'
  | 'capability.snapshotUpdated'
  | 'capability.noApiKeyError'
  | 'capability.genericJobError'
  | 'capability.actualModel'
  | 'capability.redirectTests'
  | 'capability.redirectTestsDesc'
  | 'orchestration.title'
  | 'orchestration.multiChannel'
  | 'orchestration.singleChannel'
  | 'orchestration.searchPlaceholder'
  | 'orchestration.failoverSequence'
  | 'orchestration.dragHint'
  | 'orchestration.openWebsite'
  | 'orchestration.requests'
  | 'orchestration.cache'
  | 'orchestration.requestStats'
  | 'orchestration.cacheStats'
  | 'orchestration.minutes15'
  | 'orchestration.hour1'
  | 'orchestration.hours6'
  | 'orchestration.hours24'
  | 'orchestration.endingSoon'
  | 'orchestration.minutesRemaining'
  | 'orchestration.hitRate'
  | 'orchestration.read'
  | 'orchestration.write'
  | 'orchestration.resume'
  | 'orchestration.logs'
  | 'orchestration.edit'
  | 'orchestration.enable'
  | 'orchestration.copyConfig'
  | 'orchestration.promotion'
  | 'orchestration.moveTop'
  | 'orchestration.moveBottom'
  | 'orchestration.resumeReset'
  | 'orchestration.pause'
  | 'orchestration.moveToPool'
  | 'orchestration.delete'
  | 'orchestration.keepOne'
  | 'orchestration.noActiveChannels'
  | 'orchestration.enableFromPool'
  | 'orchestration.standbyPool'
  | 'orchestration.appendToFailover'
  | 'orchestration.noMatchingStandby'
  | 'orchestration.allActive'
  | 'orchestration.copied'
  | 'orchestration.copyFailed'
  | 'orchestration.promotionSuccess'
  | 'orchestration.resumeSuccess'
  | 'orchestration.resumeSuccessWithKeys'
  | 'orchestration.deleteActiveGuard'
  | 'orchestration.blacklistedKeys'
  | 'addChannel.editTitle'
  | 'addChannel.createTitle'
  | 'addChannel.editSubtitle'
  | 'addChannel.quickSubtitle'
  | 'addChannel.fullSubtitle'
  | 'addChannel.testCapability'
  | 'addChannel.detailedMode'
  | 'addChannel.quickMode'
  | 'addChannel.quickInputLabel'
  | 'addChannel.quickInputPlaceholder'
  | 'addChannel.baseUrl'
  | 'addChannel.enterValidUrl'
  | 'addChannel.expectedRequest'
  | 'addChannel.count'
  | 'addChannel.apiKeys'
  | 'addChannel.detectedKeys'
  | 'addChannel.enterApiKey'
  | 'addChannel.channelName'
  | 'addChannel.channelType'
  | 'addChannel.nameLabel'
  | 'addChannel.namePlaceholder'
  | 'addChannel.serviceTypeLabel'
  | 'addChannel.baseUrlLabel'
  | 'addChannel.baseUrlPlaceholder'
  | 'addChannel.websiteLabel'
  | 'addChannel.websitePlaceholder'
  | 'addChannel.modelRedirect'
  | 'addChannel.autoConvertModelNames'
  | 'addChannel.oneClickSetup'
  | 'addChannel.modelHint'
  | 'addChannel.modelHintTip'
  | 'addChannel.sourceModelLabel'
  | 'addChannel.sourceModelPlaceholder'
  | 'addChannel.targetModelLabel'
  | 'addChannel.reasoningEffortLabel'
  | 'addChannel.reasoningParamStyleLabel'
  | 'addChannel.reasoningParamStyleHint'
  | 'addChannel.fastMode'
  | 'addChannel.fastModeHint'
  | 'addChannel.textVerbosityLabel'
  | 'addChannel.supportedModelsLabel'
  | 'addChannel.supportedModelsPlaceholder'
  | 'addChannel.supportedModelsHint'
  | 'addChannel.supportedModelsInvalidPattern'
  | 'addChannel.commonFilters'
  | 'addChannel.apiKeyRequired'
  | 'addChannel.apiKeyLoadBalance'
  | 'addChannel.checking'
  | 'addChannel.modelsCount'
  | 'addChannel.duplicateKey'
  | 'addChannel.deleteKey'
  | 'addChannel.addNewApiKey'
  | 'addChannel.addNewApiKeyPlaceholder'
  | 'addChannel.descriptionLabel'
  | 'addChannel.descriptionHint'
  | 'addChannel.skipTlsLabel'
  | 'addChannel.skipTlsHint'
  | 'addChannel.lowQualityLabel'
  | 'addChannel.lowQualityHint'
  | 'addChannel.autoBlacklistBalanceLabel'
  | 'addChannel.autoBlacklistBalanceHint'
  | 'addChannel.codexNativeToolPassthroughLabel'
  | 'addChannel.codexNativeToolPassthroughHint'
  | 'addChannel.codexToolCompatLabel'
  | 'addChannel.codexToolCompatHint'
  | 'addChannel.normalizeMetadataUserIdLabel'
  | 'addChannel.normalizeMetadataUserIdHint'
  | 'addChannel.normalizeNonstandardChatRolesLabel'
  | 'addChannel.normalizeNonstandardChatRolesHint'
  | 'addChannel.stripCodexClientToolsLabel'
  | 'addChannel.stripCodexClientToolsHint'
  | 'addChannel.injectDummyThoughtSignatureLabel'
  | 'addChannel.injectDummyThoughtSignatureHint'
  | 'addChannel.stripThoughtSignatureLabel'
  | 'addChannel.stripThoughtSignatureHint'
  | 'addChannel.noVisionLabel'
  | 'addChannel.noVisionHint'
  | 'addChannel.visionDisabled'
  | 'addChannel.visionEnabled'
  | 'addChannel.visionChannelEnabled'
  | 'addChannel.visionFallbackLabel'
  | 'addChannel.visionFallbackPlaceholder'
  | 'addChannel.visionFallbackHint'
  | 'addChannel.passbackReasoningContentLabel'
  | 'addChannel.passbackReasoningContentHint'
  | 'addChannel.customHeadersLabel'
  | 'addChannel.customHeadersHint'
  | 'addChannel.headerNameLabel'
  | 'addChannel.headerValueLabel'
  | 'addChannel.rpmLabel'
  | 'addChannel.rpmHint'
  | 'addChannel.proxyUrlLabel'
  | 'addChannel.proxyUrlPlaceholder'
  | 'addChannel.proxyUrlHint'
  | 'addChannel.routePrefixLabel'
  | 'addChannel.routePrefixPlaceholder'
  | 'addChannel.routePrefixHint'
  | 'addChannel.createChannel'
  | 'addChannel.updateChannel'
  | 'addChannel.modelMappingHintChat'
  | 'addChannel.modelMappingHintGemini'
  | 'addChannel.modelMappingHintResponses'
  | 'addChannel.modelMappingHintMessages'
  | 'addChannel.targetModelPlaceholderChat'
  | 'addChannel.targetModelPlaceholderResponses'
  | 'addChannel.targetModelPlaceholderGemini'
  | 'addChannel.targetModelPlaceholderMessages'
  | 'addChannel.reasoningDefault'
  | 'addChannel.sourceModelNameTooLong'
  | 'addChannel.sourceModelNoSpaces'
  | 'addChannel.sourceModelInvalidChars'
  | 'addChannel.fieldRequired'
  | 'addChannel.invalidUrl'
  | 'addChannel.atLeastOneUrl'
  | 'addChannel.invalidUrlValue'
  | 'addChannel.duplicateKeyExists'
  | 'addChannel.fillBaseUrlAndApiKey'
  | 'addChannel.allApiKeysModelsFailed'
  | 'addChannel.unknownError'
  | 'channelCard.openWebsite'
  | 'channelCard.disabled'
  | 'channelCard.suspended'
  | 'channelCard.apiKeyManagement'
  | 'channelCard.configuredKeys'
  | 'channelCard.moveTop'
  | 'channelCard.moveBottom'
  | 'channelCard.copied'
  | 'channelCard.copyKey'
  | 'channelCard.noApiKeys'
  | 'channelCard.disabledKeys'
  | 'channelCard.restoreKey'
  | 'channelCard.blacklistReason.authentication_error'
  | 'channelCard.blacklistReason.permission_error'
  | 'channelCard.blacklistReason.insufficient_balance'
  | 'channelCard.blacklistReason.unavailable'
  | 'channelCard.blacklistReason.rate_limited'
  | 'channelCard.blacklistReason.invalid'
  | 'channelCard.blacklistReason.unknown'
  | 'channelCard.notChecked'
  | 'channelCard.statusHealthy'
  | 'channelCard.statusError'
  | 'channelCard.tooltipHealthy'
  | 'channelCard.tooltipError'
  | 'channelCard.tooltipUnknown'
  | 'channelCard.noVision'
  | 'channelCard.hasVision'
  | 'channelLogs.title'
  | 'channelLogs.autoRefresh'
  | 'channelLogs.autoRefreshing'
  | 'channelLogs.empty'
  | 'channelLogs.retry'
  | 'channelLogs.sourceCapabilityTest'
  | 'channelLogs.duration.connect'
  | 'channelLogs.duration.firstByte'
  | 'channelLogs.duration.total'
  | 'channelLogs.status.pending'
  | 'channelLogs.status.connecting'
  | 'channelLogs.status.firstByte'
  | 'channelLogs.status.streaming'
  | 'channelLogs.status.completed'
  | 'channelLogs.status.failed'
  | 'channelLogs.status.cancelled'
  | 'store.channel.updated'
  | 'store.channel.added'
  | 'store.channel.deleted'
  | 'store.channel.quickAddPrioritized'
  | 'store.channel.pinging'
  | 'store.channel.autoRefreshFailed'
  | 'service.authFailed'
  | 'chart.close'
  | 'chart.1h'
  | 'chart.6h'
  | 'chart.24h'
  | 'chart.today'
  | 'chart.7d'
  | 'chart.30d'
  | 'chart.traffic'
  | 'chart.tokens'
  | 'chart.cacheRw'
  | 'chart.totalRequests'
  | 'chart.successRate'
  | 'chart.inputTokens'
  | 'chart.outputTokens'
  | 'chart.input'
  | 'chart.output'
  | 'chart.requestUnit'
  | 'chart.issueCount'
  | 'chart.total'
  | 'chart.collapse'
  | 'chart.noModelRequestsInRange'
  | 'chart.historyLoadFailed'
  | 'chart.modelStatsLoadFailed'
  | 'chart.globalStatsLoadFailed'
  | 'chart.keyHistoryLoadFailed'
  | 'chart.noRequestsInRange'
  | 'chart.noKeyUsageInRange'
  | 'status.normal'
  | 'status.tripped'
  | 'status.disabled'
  | 'status.error'
  | 'status.unknown'
  | 'status.metrics.requests'
  | 'status.metrics.successRate'
  | 'status.metrics.lastSuccess'
  | 'status.metrics.lastFailure'
  | 'status.metrics.noData'
  | 'status.metrics.justNow'
  | 'status.metrics.minutesAgo'
  | 'status.metrics.hoursAgo'
  | 'system.running'
  | 'system.runningDesc'
  | 'system.error'
  | 'system.errorDesc'
  | 'system.connecting'
  | 'system.connectingDesc'
  | 'system.unknown'
  | 'toast.confirmDeleteChannel'
  | 'toast.apiKeyAdded'
  | 'toast.apiKeyAddFailed'
  | 'toast.confirmDeleteApiKey'
  | 'toast.apiKeyDeleted'
  | 'toast.apiKeyDeleteFailed'
  | 'toast.latencyFailed'
  | 'toast.capabilityFailed'
  | 'toast.sourceChannelMissing'
  | 'toast.unsupportedProtocol'
  | 'toast.channelCopied'
  | 'toast.copyFailed'
  | 'toast.batchLatencyFailed'
  | 'toast.loadFuzzyFailed'
  | 'toast.fuzzyUnknown'
  | 'toast.fuzzyToggled'
  | 'toast.fuzzyToggleFailed'
  | 'toast.loadBillingFailed'
  | 'toast.billingUnknown'
  | 'toast.billingToggled'
  | 'toast.billingToggleFailed'
  | 'toast.enterAccessKeyContinue'
  | 'toast.savedKeyInvalid'
  | 'toast.cannotVerifyAccessKey'
  | 'toast.enterAccessKey'
  | 'toast.tooManyAttemptsSeconds'
  | 'toast.tooManyAttempts'
  | 'toast.accessKeyInvalidRemaining'
  | 'toast.loggedOut'
  | 'toast.authInvalid'
  | 'toast.operationFailed'
  | 'tooltip.loadFailedRefresh'
  | 'tooltip.billingEnabled'
  | 'tooltip.billingDisabled'
  | 'tooltip.fuzzyEnabled'
  | 'tooltip.fuzzyDisabled'
  | 'update.title'
  | 'update.currentVersion'
  | 'update.latestVersion'
  | 'update.upToDate'
  | 'update.available'
  | 'update.checking'
  | 'update.checkFailed'
  | 'update.applyBtn'
  | 'update.applying'
  | 'update.success'
  | 'update.restarting'
  | 'update.restartTimeout'
  | 'update.dockerHint'
  | 'update.permissionDenied'
  | 'update.checkBtn'

export const messages: Record<SupportedLocale, Record<MessageKey, string>> = {
  en: {
    'app.auth.verifyingTitle': 'Verifying access',
    'app.auth.verifyingBody': 'Authenticating with the saved access key...',
    'app.auth.inputLabel': 'Admin access key',
    'app.auth.inputRequired': 'Please enter the admin access key',
    'app.auth.submit': 'Open admin console',
    'app.auth.securityTitle': 'Security notice:',
    'app.auth.securityItem1': 'The admin console uses ADMIN_ACCESS_KEY; it falls back to PROXY_ACCESS_KEY if unset.',
    'app.auth.securityItem2': 'The key is stored locally and will be reused for automatic sign-in.',
    'app.auth.securityItem3': 'Do not share your access key with others.',
    'app.auth.securityItem4': 'Change the server config immediately if you suspect a leak.',
    'app.auth.securityItem5': 'After {attempts} failed attempts, access is locked for 5 minutes.',
    'app.tabs.messages': 'Claude',
    'app.tabs.chat': 'OpenAI Chat',
    'app.tabs.responses': 'Codex',
    'app.tabs.gemini': 'Gemini',
    'app.tabs.images': 'Images',
    'app.tabs.conversations': 'Cockpit',
    'cockpit.overrideActive': 'Custom channel order is active. Auto-reset in {time}',
    'cockpit.restoreDefault': 'Restore default order',
    'cockpit.empty': 'No active flights. Conversations will appear on radar when requests pass through the gateway.',
    'app.header.logout': 'Logout',
    'app.stats.trafficTitle': '{tab} traffic',
    'app.stats.totalChannels': 'Total channels',
    'app.stats.totalChannelsDesc': 'Configured API channels',
    'app.stats.activeChannels': 'Active channels',
    'app.stats.activeChannelsDesc': 'Participating in failover scheduling',
    'app.stats.systemStatus': 'System status',
    'app.actions.addChannel': 'Add channel',
    'app.actions.ping': 'Test latency',
    'app.actions.refresh': 'Refresh',
    'app.dialog.addApiKeyTitle': 'Add API key',
    'app.dialog.apiKeyLabel': 'API key',
    'app.dialog.apiKeyPlaceholder': 'Enter API key',
    'app.actions.cancel': 'Cancel',
    'app.actions.add': 'Add',
    'common.enabled': 'enabled',
    'common.disabled': 'disabled',
    'common.autoGenerated': 'Auto generated',
    'channels.empty.title': 'No channels yet',
    'channels.empty.description': 'No API channel is configured yet. Add your first channel to start using the proxy service.',
    'channels.empty.button': 'Add first channel',
    'capability.title': 'Capability test - {channel}',
    'capability.fetchingModels': 'Fetching model list...',
    'capability.selectModels': 'Select models to test',
    'capability.selectAll': 'Select all',
    'capability.deselectAll': 'Deselect all',
    'capability.noModelsFound': 'No models found. Add models manually below.',
    'capability.addModelLabel': 'Add model',
    'capability.addModelPlaceholder': 'e.g. claude-sonnet-4-6',
    'capability.startTest': 'Start test',
    'capability.loadingTitle': 'Testing protocol compatibility...',
    'capability.notStarted': 'Not started',
    'capability.rpmLabel': 'Test RPM',
    'capability.compatibleProtocols': 'Compatible protocols',
    'capability.noCompatibleProtocols': 'No compatible protocols',
    'capability.table.protocol': 'Protocol',
    'capability.table.status': 'Status',
    'capability.table.successCount': 'Success/Total',
    'capability.table.latency': 'Latency',
    'capability.table.streaming': 'Streaming',
    'capability.table.actions': 'Actions',
    'capability.modelDetails': 'Model details',
    'capability.modelDetailsUnavailable': 'Model details unavailable',
    'capability.attemptedModels': 'Attempted models: {count}',
    'capability.startedAt': 'Started at',
    'capability.testedAt': 'Finished at',
    'capability.success': 'Success',
    'capability.failed': 'Failed',
    'capability.failedTooltip': 'Test failed',
    'capability.tooltipLatency': 'Latency',
    'capability.tooltipStreaming': 'Streaming',
    'capability.modelsLabel': 'Models:',
    'capability.supported': 'Supported',
    'capability.unsupported': 'Unsupported',
    'capability.copyToTab': 'Copy to this tab',
    'capability.currentTab': 'Current tab',
    'capability.convert': '{protocol} convert',
    'capability.channelFallback': 'Channel #{id}',
    'capability.progressSummary': '{done}/{total} models finished',
    'capability.protocolRunning': 'Running',
    'capability.modelStatus': 'Status',
    'capability.modelQueued': 'Queued',
    'capability.modelRunning': 'Running',
    'capability.modelSuccess': 'Available',
    'capability.modelFailed': 'Failed',
    'capability.modelSkipped': 'Skipped',
    'capability.cancel': 'Cancel Test',
    'capability.cancelling': 'Cancelling...',
    'capability.cancelled': 'Cancelled',
    'capability.partial': 'Partially available',
    'capability.runModeCacheHit': 'Cached result',
    'capability.runModeReusedRunning': 'Reused running task',
    'capability.runModeResumedCancelled': 'Resumed cancelled task',
    'capability.runModeReusedPreviousResults': 'Reused previous success',
    'capability.reasonNotRun': 'Not executed in this round',
    'capability.reasonCancelled': 'Cancelled before completion',
    'capability.reasonTimeout': 'Timed out',
    'capability.retryModel': 'Retry this model',
    'capability.testModel': 'Click to test',
    'capability.snapshotUpdated': 'Updated: {time}',
    'capability.noApiKeyError': 'This channel has no API key configured and cannot run capability tests.',
    'capability.genericJobError': 'Capability test failed: {message}',
    'capability.actualModel': 'Actual model',
    'capability.redirectTests': 'Model Redirect Tests',
    'capability.redirectTestsDesc': 'Cross-protocol model mapping verification',
    'orchestration.title': 'Channel orchestration',
    'orchestration.multiChannel': 'Multi-channel mode',
    'orchestration.singleChannel': 'Single-channel mode',
    'orchestration.searchPlaceholder': 'Search channels...',
    'orchestration.failoverSequence': 'Failover sequence',
    'orchestration.dragHint': 'Drag to change priority, saved automatically',
    'orchestration.openWebsite': 'Open website',
    'orchestration.requests': 'requests',
    'orchestration.cache': 'Cache',
    'orchestration.requestStats': 'Request stats',
    'orchestration.cacheStats': 'Cache stats (Token)',
    'orchestration.minutes15': '15 min',
    'orchestration.hour1': '1 hour',
    'orchestration.hours6': '6 hours',
    'orchestration.hours24': '24 hours',
    'orchestration.endingSoon': 'Ending soon',
    'orchestration.minutesRemaining': '{count} min',
    'orchestration.hitRate': 'Hit',
    'orchestration.read': 'Read',
    'orchestration.write': 'Write',
    'orchestration.resume': 'Resume',
    'orchestration.logs': 'Logs',
    'orchestration.edit': 'Edit',
    'orchestration.enable': 'Enable',
    'orchestration.copyConfig': 'Copy config',
    'orchestration.promotion': 'Boost priority (5 min)',
    'orchestration.moveTop': 'Move to top',
    'orchestration.moveBottom': 'Move to bottom',
    'orchestration.resumeReset': 'Resume (reset metrics)',
    'orchestration.pause': 'Pause',
    'orchestration.moveToPool': 'Move to standby pool',
    'orchestration.delete': 'Delete',
    'orchestration.keepOne': '(keep at least one)',
    'orchestration.noActiveChannels': 'No active channels',
    'orchestration.enableFromPool': 'Enable channels from the standby pool below',
    'orchestration.standbyPool': 'Standby pool',
    'orchestration.appendToFailover': 'Once enabled, it will be appended to the end of the failover sequence',
    'orchestration.noMatchingStandby': 'No matching standby channels',
    'orchestration.allActive': 'All channels are active',
    'orchestration.copied': 'Copied',
    'orchestration.copyFailed': 'Failed to copy channel config',
    'orchestration.promotionSuccess': 'Channel {name} is now top priority and will be preferred for the next 5 minutes',
    'orchestration.resumeSuccess': 'Channel resumed and metrics reset',
    'orchestration.resumeSuccessWithKeys': 'Channel resumed, metrics reset, and {count} blacklisted key(s) restored',
    'orchestration.deleteActiveGuard': 'Cannot delete: keep at least one active channel in the failover sequence',
    'orchestration.blacklistedKeys': '{count} key(s) blacklisted',
    'addChannel.editTitle': 'Edit channel',
    'addChannel.createTitle': 'Add new channel',
    'addChannel.editSubtitle': 'Modify channel configuration',
    'addChannel.quickSubtitle': 'Quick batch add API keys',
    'addChannel.fullSubtitle': 'Configure channel details and keys',
    'addChannel.testCapability': 'Capability test',
    'addChannel.detailedMode': 'Detailed config',
    'addChannel.quickMode': 'Quick add',
    'addChannel.quickInputLabel': 'Input content',
    'addChannel.quickInputPlaceholder': 'Enter one API key or Base URL per line\n\nExample:\nsk-xxx-your-api-key\nsk-yyy-another-key\nhttps://api.example.com/v1',
    'addChannel.baseUrl': 'Base URL',
    'addChannel.enterValidUrl': 'Enter a valid URL (https://...)',
    'addChannel.expectedRequest': 'Expected request:',
    'addChannel.count': '{count}',
    'addChannel.apiKeys': 'API keys',
    'addChannel.detectedKeys': '{count} keys detected',
    'addChannel.enterApiKey': 'Enter at least one API key',
    'addChannel.channelName': 'Channel name',
    'addChannel.channelType': 'Channel type',
    'addChannel.nameLabel': 'Channel name *',
    'addChannel.namePlaceholder': 'Example: GPT-4 channel',
    'addChannel.serviceTypeLabel': 'Service type *',
    'addChannel.baseUrlLabel': 'Base URL *',
    'addChannel.baseUrlPlaceholder': 'One URL per line, supports multiple Base URLs\nExample:\nhttps://api.openai.com/v1\nhttps://api2.openai.com/v1',
    'addChannel.websiteLabel': 'Website / console (optional)',
    'addChannel.websitePlaceholder': 'Example: https://platform.openai.com',
    'addChannel.modelRedirect': 'Model redirect (optional)',
    'addChannel.autoConvertModelNames': 'Automatically convert model names',
    'addChannel.oneClickSetup': 'One-click setup',
    'addChannel.modelHint': 'Configure source model to target model mapping here.',
    'addChannel.modelHintTip': 'Click a target model field to load supported upstream models. Detection status for each API key appears in the key list.',
    'addChannel.sourceModelLabel': 'Source model',
    'addChannel.sourceModelPlaceholder': 'Select or enter a source model',
    'addChannel.targetModelLabel': 'Target model',
    'addChannel.reasoningEffortLabel': 'Reasoning effort',
    'addChannel.fastMode': 'Fast mode',
    'addChannel.fastModeHint': 'When enabled, requests send service_tier=priority.',
    'addChannel.reasoningParamStyleLabel': 'Reasoning parameter style',
    'addChannel.reasoningParamStyleHint': 'Choose whether OpenAI-style upstream requests use reasoning.effort or reasoning_effort.',
    'addChannel.textVerbosityLabel': 'Output verbosity',
    'addChannel.supportedModelsLabel': 'Supported models (optional)',
    'addChannel.supportedModelsPlaceholder': 'Press Enter after each rule, for example gpt-4*, *image*, or !*image*',
    'addChannel.supportedModelsHint': 'Matches the original model requested by the client before model redirect is applied. Leave empty to allow all models. Supported forms: exact, prefix*, *suffix, *contains*, and exclusion with !.',
    'addChannel.supportedModelsInvalidPattern': 'Invalid rule ignored. Only exact, prefix*, *suffix, *contains*, and ! exclusion are allowed.',
    'addChannel.commonFilters': 'Common filters',
    'addChannel.apiKeyRequired': 'At least one key is required',
    'addChannel.apiKeyLoadBalance': 'Multiple keys can be added for load balancing',
    'addChannel.checking': 'Checking...',
    'addChannel.modelsCount': 'models {statusCode} ({count})',
    'addChannel.duplicateKey': 'Duplicate key',
    'addChannel.deleteKey': 'Delete key',
    'addChannel.addNewApiKey': 'Add a new API key',
    'addChannel.addNewApiKeyPlaceholder': 'Enter the full API key',
    'addChannel.descriptionLabel': 'Description (optional)',
    'addChannel.descriptionHint': 'Optional channel description...',
    'addChannel.skipTlsLabel': 'Skip TLS certificate verification',
    'addChannel.skipTlsHint': 'Enable temporarily only for self-signed certificates or domain mismatch. Keep disabled in production.',
    'addChannel.lowQualityLabel': 'Low-quality channel',
    'addChannel.lowQualityHint': 'When enabled, token usage is force-estimated locally and the local value is used if the deviation exceeds 5%.',
    'addChannel.autoBlacklistBalanceLabel': 'Auto blacklist on insufficient balance',
    'addChannel.autoBlacklistBalanceHint': 'Automatically move the key to the blacklist when the upstream reports insufficient balance.',
    'addChannel.codexNativeToolPassthroughLabel': 'Codex native tool passthrough',
    'addChannel.codexNativeToolPassthroughHint': 'Convert Codex native tools (apply_patch, namespace, etc.) to OpenAI function format in passthrough mode, so upstream models can invoke them.',
    'addChannel.codexToolCompatLabel': 'Codex tools compatibility',
    'addChannel.codexToolCompatHint': 'Enable Codex CLI compatibility: strip client-only tools for Responses passthrough upstreams, or convert them to function proxy tools for Chat/Claude/Gemini upstreams.',
    'addChannel.normalizeMetadataUserIdLabel': 'Normalize metadata.user_id',
    'addChannel.normalizeMetadataUserIdHint': 'Auto-convert JSON object user_id to a flat string for upstream compatibility.',
    'addChannel.normalizeNonstandardChatRolesLabel': 'Normalize non-standard chat roles',
    'addChannel.normalizeNonstandardChatRolesHint': 'When enabled, roles outside system/user/assistant/tool are sent upstream as user.',
    'addChannel.stripCodexClientToolsLabel': 'Strip Codex client tools',
    'addChannel.stripCodexClientToolsHint': 'Enable only for legacy Responses upstreams that reject Codex CLI 0.130+ tool schemas.',
    'addChannel.injectDummyThoughtSignatureLabel': 'Inject dummy thought signature',
    'addChannel.injectDummyThoughtSignatureHint': 'Injects a dummy signature into functionCall for third-party APIs that require this field. Disable it for the official API.',
    'addChannel.stripThoughtSignatureLabel': 'Strip thought signature',
    'addChannel.stripThoughtSignatureHint': 'Removes thought_signature from functionCall for older Gemini APIs that do not support it.',
    'addChannel.noVisionLabel': 'No vision support (entire channel)',
    'addChannel.noVisionHint': 'When enabled, requests with images will skip this channel and failover to the next',
    'addChannel.visionDisabled': 'This model does not support image input',
    'addChannel.visionEnabled': 'This model supports image input',
    'addChannel.visionChannelEnabled': 'This channel supports image input',
    'addChannel.visionFallbackLabel': 'Vision fallback model',
    'addChannel.visionFallbackPlaceholder': 'Model to use when request contains images',
    'addChannel.visionFallbackHint': 'When a request contains images and the target model does not support vision, this model will be used instead. Leave empty to failover to the next channel.',
    'addChannel.passbackReasoningContentLabel': 'Passback reasoning content',
    'addChannel.passbackReasoningContentHint': 'Convert thinking blocks to reasoning_content when forwarding to Claude-protocol upstreams that require OpenAI-style reasoning_content (e.g. mimo).',
    'addChannel.customHeadersLabel': 'Custom headers (optional)',
    'addChannel.customHeadersHint': 'Add or override HTTP headers sent to the upstream service.',
    'addChannel.headerNameLabel': 'Header name',
    'addChannel.headerValueLabel': 'Header value',
    'addChannel.rpmLabel': 'Capability test RPM',
    'addChannel.rpmHint': 'Only affects capability tests; higher RPM makes tests finish faster.',
    'addChannel.proxyUrlLabel': 'Proxy URL (optional)',
    'addChannel.proxyUrlPlaceholder': 'http://127.0.0.1:7890 or socks5://127.0.0.1:1080',
    'addChannel.proxyUrlHint': 'Supports HTTP/HTTPS/SOCKS5 proxy URLs for accessing upstream services through a proxy.',
    'addChannel.routePrefixLabel': 'Route Prefix (optional)',
    'addChannel.routePrefixPlaceholder': 'kimi',
    'addChannel.routePrefixHint': 'Access this channel via /{prefix}/v1/messages. Multiple channels can share the same prefix.',
    'addChannel.createChannel': 'Create channel',
    'addChannel.updateChannel': 'Update channel',
    'addChannel.modelMappingHintChat': 'Configure model name mapping to redirect the requested model to a target model. Example: redirect "gpt-4o" to "gpt-5.4".',
    'addChannel.modelMappingHintGemini': 'Configure model name mapping to redirect the requested model to a target model. Example: redirect "gemini-pro" to "gemini-3-pro".',
    'addChannel.modelMappingHintResponses': 'Configure model name mapping to redirect the requested model to a target model. Example: redirect "opus" to "gpt-5.4".',
    'addChannel.modelMappingHintMessages': 'Configure model name mapping to redirect the requested model to a target model. Example: redirect "opus" to "claude-sonnet-4-5-20250929".',
    'addChannel.targetModelPlaceholderChat': 'Example: gpt-5.4',
    'addChannel.targetModelPlaceholderResponses': 'Example: gpt-5.4',
    'addChannel.targetModelPlaceholderGemini': 'Example: gemini-3.1-pro',
    'addChannel.targetModelPlaceholderMessages': 'Example: claude-opus-4-6',
    'addChannel.reasoningDefault': 'Unset (default)',
    'addChannel.sourceModelNameTooLong': 'Custom model name is too long (max 50 characters)',
    'addChannel.sourceModelNoSpaces': 'Model name cannot contain spaces',
    'addChannel.sourceModelInvalidChars': 'Model name can only contain letters, numbers, hyphens, underscores, dots, slashes, colons, @, and +',
    'addChannel.fieldRequired': 'This field is required',
    'addChannel.invalidUrl': 'Please enter a valid URL',
    'addChannel.atLeastOneUrl': 'Please enter at least one URL',
    'addChannel.invalidUrlValue': 'Invalid URL: {url}',
    'addChannel.duplicateKeyExists': 'This key already exists',
    'addChannel.fillBaseUrlAndApiKey': 'Fill in Base URL and at least one API key first',
    'addChannel.allApiKeysModelsFailed': 'No API key could load the model list. Check the error shown for each API key.',
    'addChannel.unknownError': 'Unknown error',
    'channelCard.openWebsite': 'Open website',
    'channelCard.disabled': 'Disabled',
    'channelCard.suspended': 'Suspended',
    'channelCard.apiKeyManagement': 'API key management',
    'channelCard.configuredKeys': 'Configured keys',
    'channelCard.moveTop': 'Move to top',
    'channelCard.moveBottom': 'Move to bottom',
    'channelCard.copied': 'Copied!',
    'channelCard.copyKey': 'Copy key',
    'channelCard.noApiKeys': 'No API keys yet',
    'channelCard.disabledKeys': 'Blacklisted keys',
    'channelCard.restoreKey': 'Restore key',
    'channelCard.blacklistReason.authentication_error': 'Auth error',
    'channelCard.blacklistReason.permission_error': 'Permission denied',
    'channelCard.blacklistReason.insufficient_balance': 'No balance',
    'channelCard.blacklistReason.unavailable': 'Unavailable',
    'channelCard.blacklistReason.rate_limited': 'Rate limited',
    'channelCard.blacklistReason.invalid': 'Invalid key',
    'channelCard.blacklistReason.unknown': 'Unknown',
    'channelCard.notChecked': 'Not checked',
    'channelCard.statusHealthy': 'Healthy',
    'channelCard.statusError': 'Error',
    'channelCard.tooltipHealthy': 'Connection is healthy: the latest check passed.',
    'channelCard.tooltipError': 'Connection error: check the Base URL, network, or API key.',
    'channelCard.tooltipUnknown': 'Not checked yet: click "Test latency" to run a check.',
    'channelCard.noVision': 'This channel does not support image input',
    'channelCard.hasVision': 'This channel supports image input',
    'channelLogs.title': 'Channel logs - {channel}',
    'channelLogs.autoRefresh': 'Auto refresh',
    'channelLogs.autoRefreshing': 'Auto refreshing',
    'channelLogs.empty': 'No logs yet',
    'channelLogs.retry': 'Retry',
    'channelLogs.sourceCapabilityTest': 'Capability Test',
    'channelLogs.duration.connect': 'Connect',
    'channelLogs.duration.firstByte': 'First Byte',
    'channelLogs.duration.total': 'Total',
    'channelLogs.status.pending': 'Pending',
    'channelLogs.status.connecting': 'Connecting',
    'channelLogs.status.firstByte': 'First Byte',
    'channelLogs.status.streaming': 'Streaming',
    'channelLogs.status.completed': 'Completed',
    'channelLogs.status.failed': 'Failed',
    'channelLogs.status.cancelled': 'Cancelled',
    'store.channel.updated': 'Channel updated successfully',
    'store.channel.added': 'Channel added successfully',
    'store.channel.deleted': 'Channel deleted successfully',
    'store.channel.quickAddPrioritized': 'Channel {name} is now top priority and will be preferred for the next 5 minutes',
    'store.channel.pinging': 'Testing in progress',
    'store.channel.autoRefreshFailed': 'Auto refresh failed',
    'service.authFailed': 'Authentication failed. Please enter the access key again.',
    'chart.close': 'Close',
    'chart.1h': '1h',
    'chart.6h': '6h',
    'chart.24h': '24h',
    'chart.today': 'Today',
    'chart.7d': '7d',
    'chart.30d': '30d',
    'chart.traffic': 'Traffic',
    'chart.tokens': 'Tokens',
    'chart.cacheRw': 'Cache R/W',
    'chart.totalRequests': 'Total requests',
    'chart.successRate': 'Availability',
    'chart.inputTokens': 'Input tokens',
    'chart.outputTokens': 'Output tokens',
    'chart.input': 'input',
    'chart.output': 'output',
    'chart.requestUnit': 'requests',
    'chart.issueCount': 'issues',
    'chart.total': 'Total',
    'chart.collapse': 'Collapse',
    'chart.noModelRequestsInRange': 'No model request records in the selected time range',
    'chart.historyLoadFailed': 'Failed to load history data',
    'chart.modelStatsLoadFailed': 'Failed to load model statistics',
    'chart.globalStatsLoadFailed': 'Failed to load global statistics',
    'chart.keyHistoryLoadFailed': 'Failed to load key history data',
    'chart.noRequestsInRange': 'No request records in the selected time range',
    'chart.noKeyUsageInRange': 'No key usage records in the selected time range',
    'status.normal': 'Normal',
    'status.tripped': 'Tripped',
    'status.disabled': 'Disabled',
    'status.error': 'Error',
    'status.unknown': 'Unknown',
    'status.metrics.requests': 'Requests',
    'status.metrics.successRate': 'Availability',
    'status.metrics.lastSuccess': 'Recent success',
    'status.metrics.lastFailure': 'Recent issue',
    'status.metrics.noData': 'No metrics yet',
    'status.metrics.justNow': 'just now',
    'status.metrics.minutesAgo': '{count} min ago',
    'status.metrics.hoursAgo': '{count} h ago',
    'system.running': 'Running',
    'system.runningDesc': 'Service is operating normally',
    'system.error': 'Connection error',
    'system.errorDesc': 'Unable to reach backend',
    'system.connecting': 'Connecting',
    'system.connectingDesc': 'Connecting to backend',
    'system.unknown': 'Unknown',
    'toast.confirmDeleteChannel': 'Delete this channel?',
    'toast.apiKeyAdded': 'API key added successfully',
    'toast.apiKeyAddFailed': 'Failed to add API key: {message}',
    'toast.confirmDeleteApiKey': 'Delete this API key?',
    'toast.apiKeyDeleted': 'API key deleted successfully',
    'toast.apiKeyDeleteFailed': 'Failed to delete API key: {message}',
    'toast.latencyFailed': 'Latency test failed: {message}',
    'toast.capabilityFailed': 'Capability test failed: {message}',
    'toast.sourceChannelMissing': 'Source channel was not found',
    'toast.unsupportedProtocol': 'Unsupported target protocol: {protocol}',
    'toast.channelCopied': 'Channel copied to {protocol} tab',
    'toast.copyFailed': 'Failed to copy channel: {message}',
    'toast.batchLatencyFailed': 'Batch latency test failed: {message}',
    'toast.loadFuzzyFailed': 'Failed to load fuzzy mode status. Refresh and try again.',
    'toast.fuzzyUnknown': 'Fuzzy mode status is unknown. Refresh first.',
    'toast.fuzzyToggled': 'Fuzzy mode {state}',
    'toast.fuzzyToggleFailed': 'Failed to toggle fuzzy mode: {message}',
    'toast.loadBillingFailed': 'Failed to load strip billing header status. Refresh and try again.',
    'toast.billingUnknown': 'Strip billing header status is unknown. Refresh first.',
    'toast.billingToggled': 'Strip billing header {state}',
    'toast.billingToggleFailed': 'Failed to toggle strip billing header: {message}',
    'toast.enterAccessKeyContinue': 'Enter the access key to continue',
    'toast.savedKeyInvalid': 'The saved access key is no longer valid. Enter it again.',
    'toast.cannotVerifyAccessKey': 'Unable to verify access key: {message}',
    'toast.enterAccessKey': 'Please enter the access key',
    'toast.tooManyAttemptsSeconds': 'Too many attempts. Retry in {seconds} seconds.',
    'toast.tooManyAttempts': 'Too many attempts. Retry in 5 minutes.',
    'toast.accessKeyInvalidRemaining': 'Access key verification failed ({remaining} attempts left)',
    'toast.loggedOut': 'Logged out securely',
    'toast.authInvalid': 'Access key is invalid or expired. Enter it again.',
    'toast.operationFailed': 'Operation failed: {message}',
    'tooltip.loadFailedRefresh': 'Load failed, please refresh the page',
    'tooltip.billingEnabled': 'Enabled: automatically strips cch= billing parameters from system.',
    'tooltip.billingDisabled': 'Disabled: keeps full billing header information.',
    'tooltip.fuzzyEnabled': 'Fuzzy mode is enabled: errors are handled loosely and all channels are retried.',
    'tooltip.fuzzyDisabled': 'Fuzzy mode is disabled: upstream responses are passed through precisely.',
    'update.title': 'System Update',
    'update.currentVersion': 'Current Version',
    'update.latestVersion': 'Latest Version',
    'update.upToDate': 'You are running the latest version',
    'update.available': 'A new version is available',
    'update.checking': 'Checking for updates...',
    'update.checkFailed': 'Failed to check for updates',
    'update.applyBtn': 'Update Now',
    'update.applying': 'Updating...',
    'update.success': 'Update successful, restarting...',
    'update.restarting': 'Server is restarting, please wait...',
    'update.restartTimeout': 'Server did not restart automatically. Please check manually.',
    'update.dockerHint': 'Docker deployment detected. Please use Watchtower or pull a new image to update.',
    'update.permissionDenied': 'Insufficient permissions to update',
    'update.checkBtn': 'Check for Updates',
  },
  id: {
    'app.auth.verifyingTitle': 'Memverifikasi akses',
    'app.auth.verifyingBody': 'Mengautentikasi dengan access key yang tersimpan...',
    'app.auth.inputLabel': 'Admin access key',
    'app.auth.inputRequired': 'Masukkan admin access key',
    'app.auth.submit': 'Buka console admin',
    'app.auth.securityTitle': 'Catatan keamanan:',
    'app.auth.securityItem1': 'Console admin memakai ADMIN_ACCESS_KEY; jika kosong akan fallback ke PROXY_ACCESS_KEY.',
    'app.auth.securityItem2': 'Key disimpan secara lokal dan akan dipakai lagi untuk login otomatis.',
    'app.auth.securityItem3': 'Jangan bagikan access key ke orang lain.',
    'app.auth.securityItem4': 'Segera ubah konfigurasi server jika ada dugaan kebocoran.',
    'app.auth.securityItem5': 'Setelah {attempts} kali gagal, akses dikunci selama 5 menit.',
    'app.tabs.messages': 'Claude',
    'app.tabs.chat': 'OpenAI Chat',
    'app.tabs.responses': 'Codex',
    'app.tabs.gemini': 'Gemini',
    'app.tabs.images': 'Images',
    'app.tabs.conversations': 'Cockpit',
    'cockpit.overrideActive': 'Urutan channel kustom aktif. Otomatis kembali dalam {time}',
    'cockpit.restoreDefault': 'Pulihkan urutan default',
    'cockpit.empty': 'Belum ada sesi aktif. Percakapan akan muncul di radar saat request melewati gateway.',
    'app.header.logout': 'Keluar',
    'app.stats.trafficTitle': 'Traffic {tab}',
    'app.stats.totalChannels': 'Total channel',
    'app.stats.totalChannelsDesc': 'Channel API yang sudah dikonfigurasi',
    'app.stats.activeChannels': 'Channel aktif',
    'app.stats.activeChannelsDesc': 'Ikut dalam penjadwalan failover',
    'app.stats.systemStatus': 'Status sistem',
    'app.actions.addChannel': 'Tambah channel',
    'app.actions.ping': 'Tes latensi',
    'app.actions.refresh': 'Refresh',
    'app.dialog.addApiKeyTitle': 'Tambah API key',
    'app.dialog.apiKeyLabel': 'API key',
    'app.dialog.apiKeyPlaceholder': 'Masukkan API key',
    'app.actions.cancel': 'Batal',
    'app.actions.add': 'Tambah',
    'common.enabled': 'aktif',
    'common.disabled': 'nonaktif',
    'common.autoGenerated': 'Dibuat otomatis',
    'channels.empty.title': 'Belum ada channel',
    'channels.empty.description': 'Belum ada channel API yang dikonfigurasi. Tambahkan channel pertama untuk mulai memakai layanan proxy.',
    'channels.empty.button': 'Tambah channel pertama',
    'capability.title': 'Tes kemampuan - {channel}',
    'capability.fetchingModels': 'Mengambil daftar model...',
    'capability.selectModels': 'Pilih model untuk diuji',
    'capability.selectAll': 'Pilih semua',
    'capability.deselectAll': 'Batal pilih',
    'capability.noModelsFound': 'Tidak ada model ditemukan. Tambahkan model secara manual.',
    'capability.addModelLabel': 'Tambah model',
    'capability.addModelPlaceholder': 'cth. claude-sonnet-4-6',
    'capability.startTest': 'Mulai tes',
    'capability.loadingTitle': 'Menguji kompatibilitas protokol...',
    'capability.notStarted': 'Belum dimulai',
    'capability.rpmLabel': 'RPM tes',
    'capability.compatibleProtocols': 'Protokol kompatibel',
    'capability.noCompatibleProtocols': 'Tidak ada protokol kompatibel',
    'capability.table.protocol': 'Protokol',
    'capability.table.status': 'Status',
    'capability.table.successCount': 'Berhasil/Total',
    'capability.table.latency': 'Latensi',
    'capability.table.streaming': 'Streaming',
    'capability.table.actions': 'Aksi',
    'capability.modelDetails': 'Detail model',
    'capability.modelDetailsUnavailable': 'Detail model tidak tersedia',
    'capability.attemptedModels': 'Model dicoba: {count}',
    'capability.startedAt': 'Dimulai',
    'capability.testedAt': 'Selesai',
    'capability.success': 'Berhasil',
    'capability.failed': 'Gagal',
    'capability.failedTooltip': 'Tes gagal',
    'capability.tooltipLatency': 'Latensi',
    'capability.tooltipStreaming': 'Streaming',
    'capability.modelsLabel': 'Model:',
    'capability.supported': 'Didukung',
    'capability.unsupported': 'Tidak didukung',
    'capability.copyToTab': 'Salin ke tab ini',
    'capability.currentTab': 'Tab saat ini',
    'capability.convert': 'Konversi {protocol}',
    'capability.channelFallback': 'Channel #{id}',
    'capability.progressSummary': '{done}/{total} model selesai',
    'capability.protocolRunning': 'Berjalan',
    'capability.modelStatus': 'Status',
    'capability.modelQueued': 'Antri',
    'capability.modelRunning': 'Berjalan',
    'capability.modelSuccess': 'Tersedia',
    'capability.modelFailed': 'Gagal',
    'capability.modelSkipped': 'Dilewati',
    'capability.cancel': 'Batalkan Tes',
    'capability.cancelling': 'Membatalkan...',
    'capability.cancelled': 'Dibatalkan',
    'capability.partial': 'Sebagian tersedia',
    'capability.runModeCacheHit': 'Hasil cache',
    'capability.runModeReusedRunning': 'Gunakan ulang tugas berjalan',
    'capability.runModeResumedCancelled': 'Lanjutkan tugas yang dibatalkan',
    'capability.runModeReusedPreviousResults': 'Gunakan hasil sukses sebelumnya',
    'capability.reasonNotRun': 'Tidak dijalankan pada putaran ini',
    'capability.reasonCancelled': 'Dibatalkan sebelum selesai',
    'capability.reasonTimeout': 'Waktu habis',
    'capability.retryModel': 'Coba ulang model ini',
    'capability.testModel': 'Klik untuk menguji',
    'capability.snapshotUpdated': 'Diperbarui: {time}',
    'capability.noApiKeyError': 'Channel ini tidak memiliki API key dan tidak dapat menjalankan tes kemampuan.',
    'capability.genericJobError': 'Tes kemampuan gagal: {message}',
    'capability.actualModel': 'Model aktual',
    'capability.redirectTests': 'Tes Redirect Model',
    'capability.redirectTestsDesc': 'Verifikasi pemetaan model lintas protokol',
    'orchestration.title': 'Orkestrasi channel',
    'orchestration.multiChannel': 'Mode multi-channel',
    'orchestration.singleChannel': 'Mode single-channel',
    'orchestration.searchPlaceholder': 'Cari channel...',
    'orchestration.failoverSequence': 'Urutan failover',
    'orchestration.dragHint': 'Geser untuk ubah prioritas, tersimpan otomatis',
    'orchestration.openWebsite': 'Buka situs',
    'orchestration.requests': 'request',
    'orchestration.cache': 'Cache',
    'orchestration.requestStats': 'Statistik request',
    'orchestration.cacheStats': 'Statistik cache (Token)',
    'orchestration.minutes15': '15 menit',
    'orchestration.hour1': '1 jam',
    'orchestration.hours6': '6 jam',
    'orchestration.hours24': '24 jam',
    'orchestration.endingSoon': 'Segera berakhir',
    'orchestration.minutesRemaining': '{count} mnt',
    'orchestration.hitRate': 'Hit',
    'orchestration.read': 'Baca',
    'orchestration.write': 'Tulis',
    'orchestration.resume': 'Lanjutkan',
    'orchestration.logs': 'Log',
    'orchestration.edit': 'Edit',
    'orchestration.enable': 'Aktifkan',
    'orchestration.copyConfig': 'Salin konfigurasi',
    'orchestration.promotion': 'Naikkan prioritas (5 menit)',
    'orchestration.moveTop': 'Pindah ke atas',
    'orchestration.moveBottom': 'Pindah ke bawah',
    'orchestration.resumeReset': 'Lanjutkan (reset metrik)',
    'orchestration.pause': 'Jeda',
    'orchestration.moveToPool': 'Pindah ke pool standby',
    'orchestration.delete': 'Hapus',
    'orchestration.keepOne': '(sisakan minimal satu)',
    'orchestration.noActiveChannels': 'Belum ada channel aktif',
    'orchestration.enableFromPool': 'Aktifkan channel dari pool standby di bawah',
    'orchestration.standbyPool': 'Pool standby',
    'orchestration.appendToFailover': 'Setelah diaktifkan, channel akan ditambahkan ke akhir urutan failover',
    'orchestration.noMatchingStandby': 'Tidak ada channel standby yang cocok',
    'orchestration.allActive': 'Semua channel aktif',
    'orchestration.copied': 'Tersalin',
    'orchestration.copyFailed': 'Gagal menyalin konfigurasi channel',
    'orchestration.promotionSuccess': 'Channel {name} menjadi prioritas tertinggi dan akan diprioritaskan selama 5 menit ke depan',
    'orchestration.resumeSuccess': 'Channel dilanjutkan dan metrik direset',
    'orchestration.resumeSuccessWithKeys': 'Channel dilanjutkan, metrik direset, dan {count} key blacklist dipulihkan',
    'orchestration.deleteActiveGuard': 'Tidak bisa dihapus: urutan failover harus menyisakan minimal satu channel aktif',
    'orchestration.blacklistedKeys': '{count} key diblokir',
    'addChannel.editTitle': 'Edit channel',
    'addChannel.createTitle': 'Tambah channel baru',
    'addChannel.editSubtitle': 'Ubah konfigurasi channel',
    'addChannel.quickSubtitle': 'Tambah API key cepat secara batch',
    'addChannel.fullSubtitle': 'Atur detail channel dan key',
    'addChannel.testCapability': 'Tes kemampuan',
    'addChannel.detailedMode': 'Konfigurasi detail',
    'addChannel.quickMode': 'Tambah cepat',
    'addChannel.quickInputLabel': 'Konten input',
    'addChannel.quickInputPlaceholder': 'Masukkan satu API key atau Base URL per baris\n\nContoh:\nsk-xxx-your-api-key\nsk-yyy-another-key\nhttps://api.example.com/v1',
    'addChannel.baseUrl': 'Base URL',
    'addChannel.enterValidUrl': 'Masukkan URL yang valid (https://...)',
    'addChannel.expectedRequest': 'Request yang diharapkan:',
    'addChannel.count': '{count}',
    'addChannel.apiKeys': 'API key',
    'addChannel.detectedKeys': '{count} key terdeteksi',
    'addChannel.enterApiKey': 'Masukkan minimal satu API key',
    'addChannel.channelName': 'Nama channel',
    'addChannel.channelType': 'Tipe channel',
    'addChannel.nameLabel': 'Nama channel *',
    'addChannel.namePlaceholder': 'Contoh: channel GPT-4',
    'addChannel.serviceTypeLabel': 'Tipe layanan *',
    'addChannel.baseUrlLabel': 'Base URL *',
    'addChannel.baseUrlPlaceholder': 'Satu URL per baris, mendukung beberapa Base URL\nContoh:\nhttps://api.openai.com/v1\nhttps://api2.openai.com/v1',
    'addChannel.websiteLabel': 'Website / console (opsional)',
    'addChannel.websitePlaceholder': 'Contoh: https://platform.openai.com',
    'addChannel.modelRedirect': 'Redirect model (opsional)',
    'addChannel.autoConvertModelNames': 'Konversi nama model otomatis',
    'addChannel.oneClickSetup': 'Setup sekali klik',
    'addChannel.modelHint': 'Atur pemetaan model sumber ke model target di sini.',
    'addChannel.modelHintTip': 'Klik field model target untuk memuat model upstream yang didukung. Status deteksi tiap API key akan tampil di daftar key.',
    'addChannel.sourceModelLabel': 'Model sumber',
    'addChannel.sourceModelPlaceholder': 'Pilih atau masukkan model sumber',
    'addChannel.targetModelLabel': 'Model target',
    'addChannel.reasoningEffortLabel': 'Kedalaman reasoning',
    'addChannel.fastMode': 'Mode cepat',
    'addChannel.fastModeHint': 'Jika aktif, request akan mengirim service_tier=priority.',
    'addChannel.reasoningParamStyleLabel': 'Gaya parameter reasoning',
    'addChannel.reasoningParamStyleHint': 'Pilih apakah request upstream bergaya OpenAI memakai reasoning.effort atau reasoning_effort.',
    'addChannel.textVerbosityLabel': 'Kepadatan output',
    'addChannel.supportedModelsLabel': 'Model yang didukung (opsional)',
    'addChannel.supportedModelsPlaceholder': 'Masukkan rule lalu tekan Enter, misalnya gpt-4*、*image*、atau !*image*',
    'addChannel.supportedModelsHint': 'Mencocokkan nama model asli yang diminta client sebelum model redirect diterapkan. Kosong berarti semua model didukung. Bentuk yang didukung: exact, prefix*, *suffix, *contains*, serta exclusion dengan !.',
    'addChannel.supportedModelsInvalidPattern': 'Rule tidak valid dan diabaikan. Hanya exact, prefix*, *suffix, *contains*, serta exclusion ! yang didukung.',
    'addChannel.commonFilters': 'Filter umum',
    'addChannel.apiKeyRequired': 'Minimal satu key diperlukan',
    'addChannel.apiKeyLoadBalance': 'Beberapa key bisa ditambahkan untuk load balancing',
    'addChannel.checking': 'Sedang memeriksa...',
    'addChannel.modelsCount': 'models {statusCode} ({count})',
    'addChannel.duplicateKey': 'Key duplikat',
    'addChannel.deleteKey': 'Hapus key',
    'addChannel.addNewApiKey': 'Tambah API key baru',
    'addChannel.addNewApiKeyPlaceholder': 'Masukkan API key lengkap',
    'addChannel.descriptionLabel': 'Deskripsi (opsional)',
    'addChannel.descriptionHint': 'Deskripsi channel opsional...',
    'addChannel.skipTlsLabel': 'Lewati verifikasi sertifikat TLS',
    'addChannel.skipTlsHint': 'Aktifkan sementara hanya untuk sertifikat self-signed atau domain mismatch. Matikan di production.',
    'addChannel.lowQualityLabel': 'Channel kualitas rendah',
    'addChannel.lowQualityHint': 'Jika aktif, token akan diperkirakan secara lokal dan nilai lokal dipakai bila selisihnya lebih dari 5%.',
    'addChannel.autoBlacklistBalanceLabel': 'Blacklist otomatis saat saldo habis',
    'addChannel.autoBlacklistBalanceHint': 'Pindahkan key ke daftar blokir otomatis saat upstream melaporkan saldo tidak cukup.',
    'addChannel.codexNativeToolPassthroughLabel': 'Passthrough alat native Codex',
    'addChannel.codexNativeToolPassthroughHint': 'Konversi alat native Codex (apply_patch, namespace, dll.) ke format function OpenAI dalam mode passthrough, agar model upstream dapat memanggilnya.',
    'addChannel.codexToolCompatLabel': 'Kompatibilitas alat Codex',
    'addChannel.codexToolCompatHint': 'Aktifkan kompatibilitas Codex CLI: hapus tool khusus klien untuk upstream Responses passthrough, atau konversi menjadi tool proxy function untuk upstream Chat/Claude/Gemini.',
    'addChannel.normalizeMetadataUserIdLabel': 'Normalisasi metadata.user_id',
    'addChannel.normalizeMetadataUserIdHint': 'Otomatis ubah user_id objek JSON menjadi string datar untuk kompatibilitas upstream.',
    'addChannel.normalizeNonstandardChatRolesLabel': 'Normalisasi role chat non-standar',
    'addChannel.normalizeNonstandardChatRolesHint': 'Jika aktif, role di luar system/user/assistant/tool dikirim ke upstream sebagai user.',
    'addChannel.stripCodexClientToolsLabel': 'Hapus tool klien Codex',
    'addChannel.stripCodexClientToolsHint': 'Aktifkan hanya untuk upstream Responses lama yang menolak schema tool Codex CLI 0.130+.',
    'addChannel.injectDummyThoughtSignatureLabel': 'Sisipkan dummy thought signature',
    'addChannel.injectDummyThoughtSignatureHint': 'Menyisipkan dummy signature ke functionCall agar kompatibel dengan API pihak ketiga yang membutuhkan field ini. Matikan untuk API resmi.',
    'addChannel.stripThoughtSignatureLabel': 'Hapus thought signature',
    'addChannel.stripThoughtSignatureHint': 'Menghapus thought_signature dari functionCall untuk Gemini API lama yang belum mendukung field tersebut.',
    'addChannel.noVisionLabel': 'Tidak mendukung vision (seluruh channel)',
    'addChannel.noVisionHint': 'Jika aktif, permintaan dengan gambar akan melewati channel ini dan failover ke channel berikutnya',
    'addChannel.visionDisabled': 'Model ini tidak mendukung input gambar',
    'addChannel.visionEnabled': 'Model ini mendukung input gambar',
    'addChannel.visionChannelEnabled': 'Channel ini mendukung input gambar',
    'addChannel.visionFallbackLabel': 'Model fallback vision',
    'addChannel.visionFallbackPlaceholder': 'Model yang digunakan saat permintaan mengandung gambar',
    'addChannel.visionFallbackHint': 'Saat permintaan mengandung gambar dan model target tidak mendukung vision, model ini akan digunakan. Kosongkan untuk failover ke channel berikutnya.',
    'addChannel.passbackReasoningContentLabel': 'Teruskan reasoning content',
    'addChannel.passbackReasoningContentHint': 'Ubah thinking block menjadi reasoning_content saat diteruskan ke upstream protokol Claude yang mewajibkan reasoning_content ala OpenAI (misalnya mimo).',
    'addChannel.customHeadersLabel': 'Custom header (opsional)',
    'addChannel.customHeadersHint': 'Tambahkan atau timpa HTTP header yang dikirim ke upstream.',
    'addChannel.headerNameLabel': 'Nama header',
    'addChannel.headerValueLabel': 'Nilai header',
    'addChannel.rpmLabel': 'RPM uji kemampuan',
    'addChannel.rpmHint': 'Hanya memengaruhi uji kemampuan; RPM lebih tinggi membuat tes selesai lebih cepat.',
    'addChannel.proxyUrlLabel': 'Proxy URL (opsional)',
    'addChannel.proxyUrlPlaceholder': 'http://127.0.0.1:7890 atau socks5://127.0.0.1:1080',
    'addChannel.proxyUrlHint': 'Mendukung proxy HTTP/HTTPS/SOCKS5 untuk mengakses layanan upstream lewat proxy.',
    'addChannel.routePrefixLabel': 'Prefiks Rute (opsional)',
    'addChannel.routePrefixPlaceholder': 'kimi',
    'addChannel.routePrefixHint': 'Akses channel ini melalui /{prefix}/v1/messages. Beberapa channel bisa berbagi prefiks yang sama.',
    'addChannel.createChannel': 'Buat channel',
    'addChannel.updateChannel': 'Perbarui channel',
    'addChannel.modelMappingHintChat': 'Atur pemetaan nama model untuk mengarahkan model yang diminta ke model target. Contoh: arahkan "gpt-4o" ke "gpt-5.4".',
    'addChannel.modelMappingHintGemini': 'Atur pemetaan nama model untuk mengarahkan model yang diminta ke model target. Contoh: arahkan "gemini-pro" ke "gemini-3-pro".',
    'addChannel.modelMappingHintResponses': 'Atur pemetaan nama model untuk mengarahkan model yang diminta ke model target. Contoh: arahkan "opus" ke "gpt-5.4".',
    'addChannel.modelMappingHintMessages': 'Atur pemetaan nama model untuk mengarahkan model yang diminta ke model target. Contoh: arahkan "opus" ke "claude-sonnet-4-5-20250929".',
    'addChannel.targetModelPlaceholderChat': 'Contoh: gpt-5.4',
    'addChannel.targetModelPlaceholderResponses': 'Contoh: gpt-5.4',
    'addChannel.targetModelPlaceholderGemini': 'Contoh: gemini-3.1-pro',
    'addChannel.targetModelPlaceholderMessages': 'Contoh: claude-opus-4-6',
    'addChannel.reasoningDefault': 'Belum diatur (default)',
    'addChannel.sourceModelNameTooLong': 'Nama model kustom terlalu panjang (maksimal 50 karakter)',
    'addChannel.sourceModelNoSpaces': 'Nama model tidak boleh mengandung spasi',
    'addChannel.sourceModelInvalidChars': 'Nama model hanya boleh berisi huruf, angka, tanda minus, underscore, titik, slash, titik dua, @, dan +',
    'addChannel.fieldRequired': 'Field ini wajib diisi',
    'addChannel.invalidUrl': 'Masukkan URL yang valid',
    'addChannel.atLeastOneUrl': 'Masukkan minimal satu URL',
    'addChannel.invalidUrlValue': 'URL tidak valid: {url}',
    'addChannel.duplicateKeyExists': 'Key ini sudah ada',
    'addChannel.fillBaseUrlAndApiKey': 'Isi Base URL dan minimal satu API key terlebih dahulu',
    'addChannel.allApiKeysModelsFailed': 'Tidak ada API key yang bisa memuat daftar model. Periksa error pada masing-masing API key.',
    'addChannel.unknownError': 'Error tidak diketahui',
    'channelCard.openWebsite': 'Buka situs',
    'channelCard.disabled': 'Nonaktif',
    'channelCard.suspended': 'Ditangguhkan',
    'channelCard.apiKeyManagement': 'Manajemen API key',
    'channelCard.configuredKeys': 'Key yang dikonfigurasi',
    'channelCard.moveTop': 'Pindah ke atas',
    'channelCard.moveBottom': 'Pindah ke bawah',
    'channelCard.copied': 'Tersalin!',
    'channelCard.copyKey': 'Salin key',
    'channelCard.noApiKeys': 'Belum ada API key',
    'channelCard.disabledKeys': 'Key diblokir',
    'channelCard.restoreKey': 'Pulihkan key',
    'channelCard.blacklistReason.authentication_error': 'Auth error',
    'channelCard.blacklistReason.permission_error': 'Izin ditolak',
    'channelCard.blacklistReason.insufficient_balance': 'Saldo habis',
    'channelCard.blacklistReason.unavailable': 'Tidak tersedia',
    'channelCard.blacklistReason.rate_limited': 'Batas rate',
    'channelCard.blacklistReason.invalid': 'Key tidak valid',
    'channelCard.blacklistReason.unknown': 'Tidak diketahui',
    'channelCard.notChecked': 'Belum dicek',
    'channelCard.statusHealthy': 'Sehat',
    'channelCard.statusError': 'Error',
    'channelCard.tooltipHealthy': 'Koneksi normal: pemeriksaan terakhir berhasil.',
    'channelCard.tooltipError': 'Koneksi bermasalah: periksa Base URL, jaringan, atau API key.',
    'channelCard.tooltipUnknown': 'Belum dicek: klik "Tes latensi" untuk memeriksa.',
    'channelCard.noVision': 'Channel ini tidak mendukung input gambar',
    'channelCard.hasVision': 'Channel ini mendukung input gambar',
    'channelLogs.title': 'Log channel - {channel}',
    'channelLogs.autoRefresh': 'Refresh otomatis',
    'channelLogs.autoRefreshing': 'Sedang auto refresh',
    'channelLogs.empty': 'Belum ada log',
    'channelLogs.retry': 'Retry',
    'channelLogs.sourceCapabilityTest': 'Tes Kemampuan',
    'channelLogs.duration.connect': 'Koneksi',
    'channelLogs.duration.firstByte': 'Byte Pertama',
    'channelLogs.duration.total': 'Total',
    'channelLogs.status.pending': 'Menunggu',
    'channelLogs.status.connecting': 'Menghubungkan',
    'channelLogs.status.firstByte': 'Byte Pertama',
    'channelLogs.status.streaming': 'Streaming',
    'channelLogs.status.completed': 'Selesai',
    'channelLogs.status.failed': 'Gagal',
    'channelLogs.status.cancelled': 'Dibatalkan',
    'store.channel.updated': 'Channel berhasil diperbarui',
    'store.channel.added': 'Channel berhasil ditambahkan',
    'store.channel.deleted': 'Channel berhasil dihapus',
    'store.channel.quickAddPrioritized': 'Channel {name} menjadi prioritas tertinggi dan akan diprioritaskan selama 5 menit ke depan',
    'store.channel.pinging': 'Tes sedang berjalan',
    'store.channel.autoRefreshFailed': 'Auto refresh gagal',
    'service.authFailed': 'Autentikasi gagal. Silakan masukkan ulang access key.',
    'chart.close': 'Tutup',
    'chart.1h': '1j',
    'chart.6h': '6j',
    'chart.24h': '24j',
    'chart.today': 'Hari ini',
    'chart.7d': '7h',
    'chart.30d': '30h',
    'chart.traffic': 'Traffic',
    'chart.tokens': 'Token',
    'chart.cacheRw': 'Cache R/W',
    'chart.totalRequests': 'Total request',
    'chart.successRate': 'Ketersediaan',
    'chart.inputTokens': 'Input token',
    'chart.outputTokens': 'Output token',
    'chart.input': 'input',
    'chart.output': 'output',
    'chart.requestUnit': 'request',
    'chart.issueCount': 'masalah',
    'chart.total': 'Total',
    'chart.collapse': 'Ciutkan',
    'chart.noModelRequestsInRange': 'Tidak ada request model dalam rentang waktu yang dipilih',
    'chart.historyLoadFailed': 'Gagal memuat data histori',
    'chart.modelStatsLoadFailed': 'Gagal memuat statistik model',
    'chart.globalStatsLoadFailed': 'Gagal memuat statistik global',
    'chart.keyHistoryLoadFailed': 'Gagal memuat histori key',
    'chart.noRequestsInRange': 'Tidak ada request dalam rentang waktu yang dipilih',
    'chart.noKeyUsageInRange': 'Tidak ada penggunaan key dalam rentang waktu yang dipilih',
    'status.normal': 'Normal',
    'status.tripped': 'Terputus',
    'status.disabled': 'Nonaktif',
    'status.error': 'Error',
    'status.unknown': 'Tidak diketahui',
    'status.metrics.requests': 'Request',
    'status.metrics.successRate': 'Ketersediaan',
    'status.metrics.lastSuccess': 'Sukses terakhir',
    'status.metrics.lastFailure': 'Masalah terakhir',
    'status.metrics.noData': 'Belum ada metrik',
    'status.metrics.justNow': 'baru saja',
    'status.metrics.minutesAgo': '{count} mnt lalu',
    'status.metrics.hoursAgo': '{count} jam lalu',
    'system.running': 'Berjalan',
    'system.runningDesc': 'Layanan berjalan normal',
    'system.error': 'Koneksi gagal',
    'system.errorDesc': 'Tidak bisa terhubung ke backend',
    'system.connecting': 'Menghubungkan',
    'system.connectingDesc': 'Sedang menghubungkan ke backend',
    'system.unknown': 'Tidak diketahui',
    'toast.confirmDeleteChannel': 'Hapus channel ini?',
    'toast.apiKeyAdded': 'API key berhasil ditambahkan',
    'toast.apiKeyAddFailed': 'Gagal menambahkan API key: {message}',
    'toast.confirmDeleteApiKey': 'Hapus API key ini?',
    'toast.apiKeyDeleted': 'API key berhasil dihapus',
    'toast.apiKeyDeleteFailed': 'Gagal menghapus API key: {message}',
    'toast.latencyFailed': 'Tes latensi gagal: {message}',
    'toast.capabilityFailed': 'Tes kemampuan gagal: {message}',
    'toast.sourceChannelMissing': 'Channel sumber tidak ditemukan',
    'toast.unsupportedProtocol': 'Protokol target tidak didukung: {protocol}',
    'toast.channelCopied': 'Channel disalin ke tab {protocol}',
    'toast.copyFailed': 'Gagal menyalin channel: {message}',
    'toast.batchLatencyFailed': 'Tes latensi massal gagal: {message}',
    'toast.loadFuzzyFailed': 'Gagal memuat status fuzzy mode. Refresh lalu coba lagi.',
    'toast.fuzzyUnknown': 'Status fuzzy mode belum diketahui. Refresh dulu.',
    'toast.fuzzyToggled': 'Mode Fuzzy {state}',
    'toast.fuzzyToggleFailed': 'Gagal mengubah fuzzy mode: {message}',
    'toast.loadBillingFailed': 'Gagal memuat status strip billing header. Refresh lalu coba lagi.',
    'toast.billingUnknown': 'Status strip billing header belum diketahui. Refresh dulu.',
    'toast.billingToggled': 'Lepaskan header penagihan {state}',
    'toast.billingToggleFailed': 'Gagal mengubah strip billing header: {message}',
    'toast.enterAccessKeyContinue': 'Masukkan access key untuk lanjut',
    'toast.savedKeyInvalid': 'Access key yang tersimpan sudah tidak valid. Masukkan ulang.',
    'toast.cannotVerifyAccessKey': 'Tidak bisa memverifikasi access key: {message}',
    'toast.enterAccessKey': 'Masukkan access key',
    'toast.tooManyAttemptsSeconds': 'Terlalu banyak percobaan. Coba lagi dalam {seconds} detik.',
    'toast.tooManyAttempts': 'Terlalu banyak percobaan. Coba lagi dalam 5 menit.',
    'toast.accessKeyInvalidRemaining': 'Verifikasi access key gagal (sisa {remaining} percobaan)',
    'toast.loggedOut': 'Berhasil logout dengan aman',
    'toast.authInvalid': 'Access key tidak valid atau kedaluwarsa. Masukkan ulang.',
    'toast.operationFailed': 'Operasi gagal: {message}',
    'tooltip.loadFailedRefresh': 'Gagal memuat, silakan refresh halaman',
    'tooltip.billingEnabled': 'Aktif: otomatis menghapus parameter billing cch= dari system.',
    'tooltip.billingDisabled': 'Nonaktif: mempertahankan informasi header billing lengkap.',
    'tooltip.fuzzyEnabled': 'Fuzzy mode aktif: error diproses longgar dan semua channel akan dicoba otomatis.',
    'tooltip.fuzzyDisabled': 'Fuzzy mode nonaktif: response upstream diteruskan secara presisi.',
    'update.title': 'Pembaruan Sistem',
    'update.currentVersion': 'Versi Saat Ini',
    'update.latestVersion': 'Versi Terbaru',
    'update.upToDate': 'Anda menggunakan versi terbaru',
    'update.available': 'Versi baru tersedia',
    'update.checking': 'Memeriksa pembaruan...',
    'update.checkFailed': 'Gagal memeriksa pembaruan',
    'update.applyBtn': 'Perbarui Sekarang',
    'update.applying': 'Memperbarui...',
    'update.success': 'Pembaruan berhasil, memulai ulang...',
    'update.restarting': 'Server sedang dimulai ulang, harap tunggu...',
    'update.restartTimeout': 'Server tidak dimulai ulang secara otomatis. Silakan periksa secara manual.',
    'update.dockerHint': 'Terdeteksi deployment Docker. Gunakan Watchtower atau pull image baru untuk memperbarui.',
    'update.permissionDenied': 'Izin tidak cukup untuk memperbarui',
    'update.checkBtn': 'Periksa Pembaruan',
  },
  'zh-CN': {
    'app.auth.verifyingTitle': '正在验证访问权限',
    'app.auth.verifyingBody': '使用保存的访问密钥进行身份验证...',
    'app.auth.inputLabel': '管理访问密钥',
    'app.auth.inputRequired': '请输入管理访问密钥',
    'app.auth.submit': '访问管理界面',
    'app.auth.securityTitle': '安全提示：',
    'app.auth.securityItem1': '管理界面使用 ADMIN_ACCESS_KEY 认证；未设置时回退到 PROXY_ACCESS_KEY。',
    'app.auth.securityItem2': '密钥将安全保存在本地，下次访问将自动验证登录。',
    'app.auth.securityItem3': '请勿与他人分享您的访问密钥。',
    'app.auth.securityItem4': '如果怀疑密钥泄露，请立即更改服务器配置。',
    'app.auth.securityItem5': '连续 {attempts} 次认证失败将锁定 5 分钟。',
    'app.tabs.messages': 'Claude',
    'app.tabs.chat': 'OpenAI Chat',
    'app.tabs.responses': 'Codex',
    'app.tabs.gemini': 'Gemini',
    'app.tabs.images': 'Images',
    'app.tabs.conversations': '驾驶舱',
    'cockpit.overrideActive': '正在使用自定义渠道顺序，{time} 后自动恢复默认调度',
    'cockpit.restoreDefault': '恢复默认顺序',
    'cockpit.empty': '暂无活跃会话。请求经过网关后，会话会出现在驾驶舱雷达上。',
    'app.header.logout': '注销',
    'app.stats.trafficTitle': '{tab} 流量统计',
    'app.stats.totalChannels': '总渠道数',
    'app.stats.totalChannelsDesc': '已配置的API渠道',
    'app.stats.activeChannels': '活跃渠道',
    'app.stats.activeChannelsDesc': '参与故障转移调度',
    'app.stats.systemStatus': '系统状态',
    'app.actions.addChannel': '添加渠道',
    'app.actions.ping': '测试延迟',
    'app.actions.refresh': '刷新',
    'app.dialog.addApiKeyTitle': '添加API密钥',
    'app.dialog.apiKeyLabel': 'API密钥',
    'app.dialog.apiKeyPlaceholder': '输入API密钥',
    'app.actions.cancel': '取消',
    'app.actions.add': '添加',
    'common.enabled': '启用',
    'common.disabled': '关闭',
    'common.autoGenerated': '自动生成',
    'channels.empty.title': '暂无渠道配置',
    'channels.empty.description': '还没有配置任何API渠道，请添加第一个渠道来开始使用代理服务',
    'channels.empty.button': '添加第一个渠道',
    'capability.title': '能力测试 - {channel}',
    'capability.fetchingModels': '正在获取模型列表...',
    'capability.selectModels': '选择要测试的模型',
    'capability.selectAll': '全选',
    'capability.deselectAll': '取消全选',
    'capability.noModelsFound': '未找到模型，请在下方手动添加',
    'capability.addModelLabel': '添加模型',
    'capability.addModelPlaceholder': '例如 claude-sonnet-4-6',
    'capability.startTest': '开始测试',
    'capability.loadingTitle': '正在测试协议兼容性...',
    'capability.notStarted': '待测试',
    'capability.rpmLabel': '测试 RPM',
    'capability.compatibleProtocols': '兼容协议',
    'capability.noCompatibleProtocols': '无兼容协议',
    'capability.table.protocol': '协议',
    'capability.table.status': '状态',
    'capability.table.successCount': '成功数/总数',
    'capability.table.latency': '延迟',
    'capability.table.streaming': '流式',
    'capability.table.actions': '操作',
    'capability.modelDetails': '模型明细',
    'capability.modelDetailsUnavailable': '模型明细暂不可用',
    'capability.attemptedModels': '尝试模型数: {count}',
    'capability.startedAt': '开始时间',
    'capability.testedAt': '完成时间',
    'capability.success': '成功',
    'capability.failed': '失败',
    'capability.failedTooltip': '测试失败',
    'capability.tooltipLatency': '延迟',
    'capability.tooltipStreaming': '流式',
    'capability.modelsLabel': '模型：',
    'capability.supported': '支持',
    'capability.unsupported': '不支持',
    'capability.copyToTab': '复制到此 Tab',
    'capability.currentTab': '当前 Tab',
    'capability.convert': '{protocol} 转换',
    'capability.channelFallback': '渠道 #{id}',
    'capability.progressSummary': '{done}/{total} 已完成',
    'capability.protocolRunning': '测试中',
    'capability.modelStatus': '状态',
    'capability.modelQueued': '排队中',
    'capability.modelRunning': '测试中',
    'capability.modelSuccess': '可用',
    'capability.modelFailed': '失败',
    'capability.modelSkipped': '已跳过',
    'capability.cancel': '取消测试',
    'capability.cancelling': '取消中...',
    'capability.cancelled': '已取消',
    'capability.partial': '部分可用',
    'capability.runModeCacheHit': '缓存结果',
    'capability.runModeReusedRunning': '复用进行中任务',
    'capability.runModeResumedCancelled': '恢复已取消任务',
    'capability.runModeReusedPreviousResults': '复用上次成功结果',
    'capability.reasonNotRun': '本轮未执行',
    'capability.reasonCancelled': '完成前已取消',
    'capability.reasonTimeout': '请求超时',
    'capability.retryModel': '重测此模型',
    'capability.testModel': '点击测试',
    'capability.snapshotUpdated': '更新时间：{time}',
    'capability.noApiKeyError': '该渠道未配置 API Key，无法执行能力测试。',
    'capability.genericJobError': '能力测试失败：{message}',
    'capability.actualModel': '实际模型',
    'capability.redirectTests': '模型重定向测试',
    'capability.redirectTestsDesc': '跨协议模型映射验证',
    'orchestration.title': '渠道编排',
    'orchestration.multiChannel': '多渠道模式',
    'orchestration.singleChannel': '单渠道模式',
    'orchestration.searchPlaceholder': '搜索渠道...',
    'orchestration.failoverSequence': '故障转移序列',
    'orchestration.dragHint': '拖拽调整优先级，自动保存',
    'orchestration.openWebsite': '打开官网',
    'orchestration.requests': '请求',
    'orchestration.cache': '缓存',
    'orchestration.requestStats': '请求统计',
    'orchestration.cacheStats': '缓存统计 (Token)',
    'orchestration.minutes15': '15分钟',
    'orchestration.hour1': '1小时',
    'orchestration.hours6': '6小时',
    'orchestration.hours24': '24小时',
    'orchestration.endingSoon': '即将结束',
    'orchestration.minutesRemaining': '{count}分钟',
    'orchestration.hitRate': '命中',
    'orchestration.read': '读',
    'orchestration.write': '写',
    'orchestration.resume': '恢复',
    'orchestration.logs': '日志',
    'orchestration.edit': '编辑',
    'orchestration.enable': '启用',
    'orchestration.copyConfig': '复制配置',
    'orchestration.promotion': '抢优先级 (5分钟)',
    'orchestration.moveTop': '置顶',
    'orchestration.moveBottom': '置底',
    'orchestration.resumeReset': '恢复 (重置指标)',
    'orchestration.pause': '暂停',
    'orchestration.moveToPool': '移至备用池',
    'orchestration.delete': '删除',
    'orchestration.keepOne': '(至少保留一个)',
    'orchestration.noActiveChannels': '暂无活跃渠道',
    'orchestration.enableFromPool': '从下方备用池启用渠道',
    'orchestration.standbyPool': '备用资源池',
    'orchestration.appendToFailover': '启用后将追加到活跃序列末尾',
    'orchestration.noMatchingStandby': '无匹配的备用渠道',
    'orchestration.allActive': '所有渠道都处于活跃状态',
    'orchestration.copied': '已复制',
    'orchestration.copyFailed': '复制渠道配置失败',
    'orchestration.promotionSuccess': '渠道 {name} 已设为最高优先级，5分钟内优先使用',
    'orchestration.resumeSuccess': '渠道已恢复，熔断指标已重置',
    'orchestration.resumeSuccessWithKeys': '渠道已恢复，熔断指标已重置，并恢复了 {count} 个拉黑密钥',
    'orchestration.deleteActiveGuard': '无法删除：故障转移序列中至少需要保留一个活跃渠道',
    'orchestration.blacklistedKeys': '{count} 个密钥已拉黑',
    'addChannel.editTitle': '编辑渠道',
    'addChannel.createTitle': '添加新渠道',
    'addChannel.editSubtitle': '修改渠道配置信息',
    'addChannel.quickSubtitle': '快速批量添加 API 密钥',
    'addChannel.fullSubtitle': '配置API渠道信息和密钥',
    'addChannel.testCapability': '能力测试',
    'addChannel.detailedMode': '详细配置',
    'addChannel.quickMode': '快速添加',
    'addChannel.quickInputLabel': '输入内容',
    'addChannel.quickInputPlaceholder': '每行输入一个 API Key 或 Base URL\n\n示例:\nsk-xxx-your-api-key\nsk-yyy-another-key\nhttps://api.example.com/v1',
    'addChannel.baseUrl': 'Base URL',
    'addChannel.enterValidUrl': '请输入一个有效的 URL (https://...)',
    'addChannel.expectedRequest': '预期请求:',
    'addChannel.count': '{count} 个',
    'addChannel.apiKeys': 'API 密钥',
    'addChannel.detectedKeys': '已检测到 {count} 个密钥',
    'addChannel.enterApiKey': '请至少输入一个 API Key',
    'addChannel.channelName': '渠道名称',
    'addChannel.channelType': '渠道类型',
    'addChannel.nameLabel': '渠道名称 *',
    'addChannel.namePlaceholder': '例如：GPT-4 渠道',
    'addChannel.serviceTypeLabel': '服务类型 *',
    'addChannel.baseUrlLabel': '基础URL *',
    'addChannel.baseUrlPlaceholder': '每行一个 URL，支持多个 BaseURL\n例如：\nhttps://api.openai.com/v1\nhttps://api2.openai.com/v1',
    'addChannel.websiteLabel': '官网/控制台 (可选)',
    'addChannel.websitePlaceholder': '例如：https://platform.openai.com',
    'addChannel.modelRedirect': '模型重定向 (可选)',
    'addChannel.autoConvertModelNames': '自动转换模型名称',
    'addChannel.oneClickSetup': '一键设置',
    'addChannel.modelHint': '在此配置源模型到目标模型的映射。',
    'addChannel.modelHintTip': '点击目标模型输入框会自动获取上游支持的模型列表,每个 API Key 的检测状态会显示在密钥列表中',
    'addChannel.sourceModelLabel': '源模型名',
    'addChannel.sourceModelPlaceholder': '选择或输入源模型名',
    'addChannel.targetModelLabel': '目标模型名',
    'addChannel.reasoningEffortLabel': '思考深度',
    'addChannel.fastMode': 'Fast 模式',
    'addChannel.fastModeHint': '开启后下发 service_tier=priority',
    'addChannel.reasoningParamStyleLabel': '思考参数风格',
    'addChannel.reasoningParamStyleHint': '选择 OpenAI 风格上游请求使用 reasoning.effort 还是 reasoning_effort。',
    'addChannel.textVerbosityLabel': '输出冗长度',
    'addChannel.supportedModelsLabel': '支持的模型 (可选)',
    'addChannel.supportedModelsPlaceholder': '输入规则后按回车添加，如 gpt-4*、*image*、!*image*',
    'addChannel.supportedModelsHint': '匹配客户端请求的原始模型名（模型重定向发生在渠道选中之后）。留空表示支持所有模型。支持精确匹配、prefix*、*suffix、*contains* 以及 ! 排除规则。',
    'addChannel.supportedModelsInvalidPattern': '已忽略非法规则。仅支持精确匹配、prefix*、*suffix、*contains* 和 ! 排除规则。',
    'addChannel.commonFilters': '常用过滤器',
    'addChannel.apiKeyRequired': '至少需要一个密钥',
    'addChannel.apiKeyLoadBalance': '可添加多个密钥用于负载均衡',
    'addChannel.checking': '检测中...',
    'addChannel.modelsCount': 'models {statusCode} ({count} 个)',
    'addChannel.duplicateKey': '重复密钥',
    'addChannel.deleteKey': '删除密钥',
    'addChannel.addNewApiKey': '添加新的API密钥',
    'addChannel.addNewApiKeyPlaceholder': '输入完整的API密钥',
    'addChannel.descriptionLabel': '描述 (可选)',
    'addChannel.descriptionHint': '可选的渠道描述...',
    'addChannel.skipTlsLabel': '跳过 TLS 证书验证',
    'addChannel.skipTlsHint': '仅在自签名或域名不匹配时临时启用，生产环境请关闭',
    'addChannel.lowQualityLabel': '低质量渠道',
    'addChannel.lowQualityHint': '启用后强制本地估算 token 数量，偏差超过 5% 时使用本地值',
    'addChannel.autoBlacklistBalanceLabel': '余额不足时自动拉黑',
    'addChannel.autoBlacklistBalanceHint': '当上游返回余额不足时，自动将该 Key 移入拉黑列表。',
    'addChannel.codexNativeToolPassthroughLabel': 'Codex 原生工具透传',
    'addChannel.codexNativeToolPassthroughHint': '透传模式下将 Codex 原生工具（apply_patch、namespace 等）转换为 OpenAI function 格式，使上游模型可调用。',
    'addChannel.codexToolCompatLabel': 'Codex 工具兼容',
    'addChannel.codexToolCompatHint': '启用 Codex CLI 兼容：Responses 透传上游会剥离客户端专属工具，Chat/Claude/Gemini 上游会转换为 function 代理工具。',
    'addChannel.normalizeMetadataUserIdLabel': '规范化 metadata.user_id',
    'addChannel.normalizeMetadataUserIdHint': '自动将 JSON 对象格式的 user_id 转换为扁平字符串，确保上游兼容性。',
    'addChannel.normalizeNonstandardChatRolesLabel': '规范化非常见 Chat role',
    'addChannel.normalizeNonstandardChatRolesHint': '开启后将 system/user/assistant/tool 之外的 role 作为 user 转发给上游。',
    'addChannel.stripCodexClientToolsLabel': '剥离 Codex 客户端工具',
    'addChannel.stripCodexClientToolsHint': '仅用于不支持 Codex CLI 0.130+ 工具结构的旧版 Responses 上游，默认请关闭。',
    'addChannel.injectDummyThoughtSignatureLabel': '注入 Dummy Thought Signature',
    'addChannel.injectDummyThoughtSignatureHint': '为 functionCall 注入 dummy signature，兼容需要该字段的第三方 API（官方 API 请关闭）',
    'addChannel.stripThoughtSignatureLabel': '移除 Thought Signature',
    'addChannel.stripThoughtSignatureHint': '移除 functionCall 的 thought_signature 字段，兼容不支持该字段的旧版 Gemini API',
    'addChannel.noVisionLabel': '不支持图片输入（整个渠道）',
    'addChannel.noVisionHint': '启用后，包含图片的请求将跳过此渠道并 failover 到下一个渠道',
    'addChannel.visionDisabled': '此模型不支持图片输入',
    'addChannel.visionEnabled': '此模型支持图片输入',
    'addChannel.visionChannelEnabled': '此渠道支持图片输入',
    'addChannel.visionFallbackLabel': '视觉回退模型',
    'addChannel.visionFallbackPlaceholder': '含图请求时使用的替代模型',
    'addChannel.visionFallbackHint': '当请求包含图片且目标模型不支持 vision 时，使用此模型替代。留空则 failover 到下一个渠道。',
    'addChannel.passbackReasoningContentLabel': '回传 Reasoning Content',
    'addChannel.passbackReasoningContentHint': '将 thinking 块转为 reasoning_content 回传，兼容 mimo 等要求 OpenAI 风格 reasoning_content 的 Claude 协议上游',
    'addChannel.customHeadersLabel': '自定义请求头 (可选)',
    'addChannel.customHeadersHint': '添加或覆盖发送到上游的 HTTP 请求头',
    'addChannel.headerNameLabel': 'Header 名称',
    'addChannel.headerValueLabel': 'Header 值',
    'addChannel.rpmLabel': '能力测试 RPM',
    'addChannel.rpmHint': '仅影响模型能力测试；RPM 越高测试完成越快。',
    'addChannel.proxyUrlLabel': '代理 URL (可选)',
    'addChannel.proxyUrlPlaceholder': 'http://127.0.0.1:7890 或 socks5://127.0.0.1:1080',
    'addChannel.proxyUrlHint': '支持 HTTP/HTTPS/SOCKS5 代理，用于通过代理访问上游服务',
    'addChannel.routePrefixLabel': '路由前缀 (可选)',
    'addChannel.routePrefixPlaceholder': 'kimi',
    'addChannel.routePrefixHint': '通过 /{前缀}/v1/messages 访问此渠道，多个渠道可共享同一前缀',
    'addChannel.createChannel': '创建渠道',
    'addChannel.updateChannel': '更新渠道',
    'addChannel.modelMappingHintChat': '配置模型名称映射，将请求中的模型名重定向到目标模型。例如：将 "gpt-4o" 重定向到 "gpt-5.4"',
    'addChannel.modelMappingHintGemini': '配置模型名称映射，将请求中的模型名重定向到目标模型。例如：将 "gemini-pro" 重定向到 "gemini-3-pro"',
    'addChannel.modelMappingHintResponses': '配置模型名称映射，将请求中的模型名重定向到目标模型。例如：将 "opus" 重定向到 "gpt-5.4"',
    'addChannel.modelMappingHintMessages': '配置模型名称映射，将请求中的模型名重定向到目标模型。例如：将 "opus" 重定向到 "claude-sonnet-4-5-20250929"',
    'addChannel.targetModelPlaceholderChat': '例如：gpt-5.4',
    'addChannel.targetModelPlaceholderResponses': '例如：gpt-5.4',
    'addChannel.targetModelPlaceholderGemini': '例如：gemini-3.1-pro',
    'addChannel.targetModelPlaceholderMessages': '例如：claude-opus-4-6',
    'addChannel.reasoningDefault': '未设置（默认）',
    'addChannel.sourceModelNameTooLong': '自定义模型名过长（最多 50 字符）',
    'addChannel.sourceModelNoSpaces': '模型名不能包含空格',
    'addChannel.sourceModelInvalidChars': '模型名只能包含字母、数字、连字符、下划线、点、斜杠、冒号、@ 和 +',
    'addChannel.fieldRequired': '此字段为必填项',
    'addChannel.invalidUrl': '请输入有效的URL',
    'addChannel.atLeastOneUrl': '请至少输入一个 URL',
    'addChannel.invalidUrlValue': '无效的 URL: {url}',
    'addChannel.duplicateKeyExists': '该密钥已存在',
    'addChannel.fillBaseUrlAndApiKey': '请先填写 Base URL 和至少一个 API Key',
    'addChannel.allApiKeysModelsFailed': '所有 API Key 都无法获取模型列表，请检查 API 密钥列表中的错误信息',
    'addChannel.unknownError': '未知错误',
    'channelCard.openWebsite': '打开官网',
    'channelCard.disabled': '停用',
    'channelCard.suspended': '熔断',
    'channelCard.apiKeyManagement': 'API密钥管理',
    'channelCard.configuredKeys': '已配置的密钥',
    'channelCard.moveTop': '置顶',
    'channelCard.moveBottom': '置底',
    'channelCard.copied': '已复制!',
    'channelCard.copyKey': '复制密钥',
    'channelCard.noApiKeys': '暂无API密钥',
    'channelCard.disabledKeys': '已拉黑密钥',
    'channelCard.restoreKey': '恢复密钥',
    'channelCard.blacklistReason.authentication_error': '认证失败',
    'channelCard.blacklistReason.permission_error': '权限不足',
    'channelCard.blacklistReason.insufficient_balance': '余额不足',
    'channelCard.blacklistReason.unavailable': '不可用',
    'channelCard.blacklistReason.rate_limited': '频率限制',
    'channelCard.blacklistReason.invalid': '密钥无效',
    'channelCard.blacklistReason.unknown': '未知原因',
    'channelCard.notChecked': '未检测',
    'channelCard.statusHealthy': '健康',
    'channelCard.statusError': '错误',
    'channelCard.tooltipHealthy': '连接正常：最近一次检测通过',
    'channelCard.tooltipError': '连接异常：请检查基础 URL、网络或 API 密钥',
    'channelCard.tooltipUnknown': '尚未检测：请点击”测试延迟”进行检测',
    'channelCard.noVision': '此渠道不支持图片输入',
    'channelCard.hasVision': '此渠道支持图片输入',
    'channelLogs.title': '渠道日志 - {channel}',
    'channelLogs.autoRefresh': '自动刷新',
    'channelLogs.autoRefreshing': '自动刷新中',
    'channelLogs.empty': '暂无日志记录',
    'channelLogs.retry': '重试',
    'channelLogs.sourceCapabilityTest': '能力测试',
    'channelLogs.duration.connect': '连接',
    'channelLogs.duration.firstByte': '首字',
    'channelLogs.duration.total': '总计',
    'channelLogs.status.pending': '等待中',
    'channelLogs.status.connecting': '连接中',
    'channelLogs.status.firstByte': '首字节',
    'channelLogs.status.streaming': '传输中',
    'channelLogs.status.completed': '已完成',
    'channelLogs.status.failed': '失败',
    'channelLogs.status.cancelled': '已取消',
    'store.channel.updated': '渠道更新成功',
    'store.channel.added': '渠道添加成功',
    'store.channel.deleted': '渠道删除成功',
    'store.channel.quickAddPrioritized': '渠道 {name} 已设为最高优先级，5分钟内优先使用',
    'store.channel.pinging': '正在测试中',
    'store.channel.autoRefreshFailed': '自动刷新失败',
    'service.authFailed': '认证失败，请重新输入访问密钥',
    'chart.close': '关闭',
    'chart.1h': '1小时',
    'chart.6h': '6小时',
    'chart.24h': '24小时',
    'chart.today': '今日',
    'chart.7d': '1周',
    'chart.30d': '1月',
    'chart.traffic': '流量',
    'chart.tokens': 'Token',
    'chart.cacheRw': '缓存 R/W',
    'chart.totalRequests': '总请求',
    'chart.successRate': '可用率',
    'chart.inputTokens': '输入 Token',
    'chart.outputTokens': '输出 Token',
    'chart.input': '输入',
    'chart.output': '输出',
    'chart.requestUnit': '请求',
    'chart.issueCount': '异常',
    'chart.total': '合计',
    'chart.collapse': '收起',
    'chart.noModelRequestsInRange': '选定时间范围内没有模型请求记录',
    'chart.historyLoadFailed': '获取历史数据失败',
    'chart.modelStatsLoadFailed': '获取模型统计数据失败',
    'chart.globalStatsLoadFailed': '获取全局统计数据失败',
    'chart.keyHistoryLoadFailed': '获取 Key 历史数据失败',
    'chart.noRequestsInRange': '选定时间范围内没有请求记录',
    'chart.noKeyUsageInRange': '选定时间范围内没有 Key 使用记录',
    'status.normal': '正常',
    'status.tripped': '熔断',
    'status.disabled': '禁用',
    'status.error': '错误',
    'status.unknown': '未知',
    'status.metrics.requests': '请求数',
    'status.metrics.successRate': '可用率',
    'status.metrics.lastSuccess': '最近成功',
    'status.metrics.lastFailure': '最近异常',
    'status.metrics.noData': '暂无指标数据',
    'status.metrics.justNow': '刚刚',
    'status.metrics.minutesAgo': '{count} 分钟前',
    'status.metrics.hoursAgo': '{count} 小时前',
    'system.running': '运行中',
    'system.runningDesc': '服务正常运行',
    'system.error': '连接失败',
    'system.errorDesc': '无法连接后端',
    'system.connecting': '连接中',
    'system.connectingDesc': '正在连接后端',
    'system.unknown': '未知',
    'toast.confirmDeleteChannel': '确定要删除这个渠道吗？',
    'toast.apiKeyAdded': 'API密钥添加成功',
    'toast.apiKeyAddFailed': '添加API密钥失败: {message}',
    'toast.confirmDeleteApiKey': '确定要删除这个API密钥吗？',
    'toast.apiKeyDeleted': 'API密钥删除成功',
    'toast.apiKeyDeleteFailed': '删除API密钥失败: {message}',
    'toast.latencyFailed': '延迟测试失败: {message}',
    'toast.capabilityFailed': '能力测试失败: {message}',
    'toast.sourceChannelMissing': '找不到源渠道信息',
    'toast.unsupportedProtocol': '不支持的目标协议: {protocol}',
    'toast.channelCopied': '渠道已复制到 {protocol} Tab',
    'toast.copyFailed': '复制渠道失败: {message}',
    'toast.batchLatencyFailed': '批量延迟测试失败: {message}',
    'toast.loadFuzzyFailed': '加载 Fuzzy 模式状态失败，请刷新页面重试',
    'toast.fuzzyUnknown': 'Fuzzy 模式状态未知，请先刷新页面',
    'toast.fuzzyToggled': 'Fuzzy 模式已{state}',
    'toast.fuzzyToggleFailed': '切换 Fuzzy 模式失败: {message}',
    'toast.loadBillingFailed': '加载移除计费头状态失败，请刷新页面重试',
    'toast.billingUnknown': '移除计费头状态未知，请先刷新页面',
    'toast.billingToggled': '移除计费头已{state}',
    'toast.billingToggleFailed': '切换移除计费头失败: {message}',
    'toast.enterAccessKeyContinue': '请输入访问密钥以继续',
    'toast.savedKeyInvalid': '保存的访问密钥已失效，请重新输入',
    'toast.cannotVerifyAccessKey': '无法验证访问密钥: {message}',
    'toast.enterAccessKey': '请输入访问密钥',
    'toast.tooManyAttemptsSeconds': '认证尝试次数过多，请在 {seconds} 秒后重试',
    'toast.tooManyAttempts': '认证尝试次数过多，请在5分钟后重试',
    'toast.accessKeyInvalidRemaining': '访问密钥验证失败 (剩余尝试次数: {remaining})',
    'toast.loggedOut': '已安全注销',
    'toast.authInvalid': '访问密钥无效或已过期，请重新输入',
    'toast.operationFailed': '操作失败: {message}',
    'tooltip.loadFailedRefresh': '加载失败，请刷新页面',
    'tooltip.billingEnabled': '已启用：自动移除 system 中的 cch= 计费参数',
    'tooltip.billingDisabled': '已关闭：保留完整的计费头信息',
    'tooltip.fuzzyEnabled': 'Fuzzy 模式已启用：模糊处理错误，自动尝试所有渠道',
    'tooltip.fuzzyDisabled': 'Fuzzy 模式已关闭：精确处理错误，透传上游响应',
    'update.title': '系统更新',
    'update.currentVersion': '当前版本',
    'update.latestVersion': '最新版本',
    'update.upToDate': '已是最新版本',
    'update.available': '发现新版本',
    'update.checking': '正在检查更新...',
    'update.checkFailed': '检查更新失败',
    'update.applyBtn': '立即升级',
    'update.applying': '正在升级...',
    'update.success': '升级成功，正在重启...',
    'update.restarting': '服务器正在重启，请稍候...',
    'update.restartTimeout': '服务器未能自动重启，请手动检查',
    'update.dockerHint': '检测到 Docker 部署，请使用 Watchtower 或拉取新镜像进行更新',
    'update.permissionDenied': '权限不足，无法升级',
    'update.checkBtn': '检查更新',
  },
}
